### ISSUE TITLE
Add terms and privacy pages

### ISSUE THREAD

**Issue by adamstac** [thechangelog/changelog.com#112]

**Comment by soleo** [comment]
Just a suggestion, you could fork or create a new repo for maintaining policies. [peardeck](https://github.com/peardeck/policies) and [clever](https://github.com/clever/policies) opened their policy related docs.  I also used similar [docs](https://github.com/FancyFoodie/policies) forked from them

**Comment by adamstac** [comment]
@soleo yea we already have a [legal repo](https://github.com/thechangelog/legal) — I just need to take the time to update them and add them to the new site.

This is something easy if you wanted to do the first few steps and submit a PR to collab on around this.

**Comment by soleo** [comment]
Nice. So basically you just need someone to use the markdown files from that repo to convert to HTML. I've never written  a single line of Elixir before, but it would be find to check it out. You can assign it to me.

**Comment by soleo** [comment]
I'd be adding two routes

```
get "/privacy", PageController, :privacy
get "/terms", PageController, :terms
```

and two functions in PageController, sounds good?

**Comment by soleo** [comment]
Or would it be better if I convert the legal repo into Elixir package and introduce it as a dependency? This would definitely save some extra travel time the fetching the documents.

**Comment by jerodsanto** [comment]
@soleo adding the two routes and the appropriate template files will do (the controller functions are only necessary for pages that have special data/setup needs, which these should not need). No need to make it any more complicated than that.

**Comment by soleo** [comment]
![screenshot-localhost 4000-2016-11-12-12-39-06](https://cloud.githubusercontent.com/assets/635858/20240083/2b636e4c-a8d5-11e6-88ad-5fefd7a7c173.png)
![screenshot-localhost 8000-2016-11-12-11-40-27](https://cloud.githubusercontent.com/assets/635858/20240085/2c57c58c-a8d5-11e6-95c7-4b72741d0c1c.png)

**Comment by soleo** [comment]
cc @jerodsanto @adamstac Let me know if you need any changes. I added the links to footer, but I don't know if it is necessary to add the links to other places as well.

**Comment by jerodsanto** [comment]
donezo
