### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by sobolevn** [thechangelog/changelog.com#120]
Would you like to have a Docker image? That's great for the quick start.

I can help you with it. Let me know what are you thinking.

**Comment by jerodsanto** [comment]
Sure! I don't see why not. Once we have it we can update the readme section on getting started to have a Docker path. 🍻

**Comment by sobolevn** [comment]
I don't know what happened, but I somehow committed into your repo without access.

**Comment by jerodsanto** [comment]
@sobolevn what do you mean you committed to our repo? Your commits and PR are on your fork.

**Comment by sobolevn** [comment]
This commit is on the main repo: https://github.com/thechangelog/changelog.com/commit/5b102a7f4d0d1a178012fcae61ee79a25e5847a2

**Comment by jerodsanto** [comment]
This is weird. If you look in the [commit history](https://github.com/thechangelog/changelog.com/commits/master) or the current code your stuff isn't there. I just double checked the settings and we restrict edits to team members. Am I missing something here?

**Comment by sobolevn** [comment]
This is really weird, since I can actually browse files from my commit: https://github.com/thechangelog/changelog.com/tree/5b102a7f4d0d1a178012fcae61ee79a25e5847a2

**Comment by d2s** [comment]
Just wondering if that repository problem is somehow related to recent [Incident Report](https://github.com/blog/2273-incident-report-inadvertent-private-repository-disclosure) of GitHub platform itself. Most likely not, but that came to the mind. 😟

**Comment by adamstac** [comment]
Just a heads up -- I brought this to the attention of GitHub support. We'll see what they have to say about this. Thanks for letting us know @sobolevn so we can look into this.

**Comment by adamstac** [comment]
From GitHub:

> Hey Adam, commits from forks can be accessed from the parent repository even if they haven't been merged.

> I can understand this can be confusing but its currently expected behaviour that trees and commits from forks can be accessed from the parent repositories URL.

**Comment by sobolevn** [comment]
So, no worries. Thanks @adamstac !

**Comment by thenets** [comment]
Hi. I'm trying to do that but I can't find the database configuration. Where is the PostgreSQL settings?

This is the repo that I've created:
https://github.com/thenets/changelog-docker

To test, just install Docker and run "make build-test".

**Comment by jerodsanto** [comment]
@thenets the db config is in [config/dev.exs](https://github.com/thechangelog/changelog.com/blob/master/config/dev.exs#L36)

**Comment by thenets** [comment]
@jerodsanto I don't know how to read it.
Where is the username and password field?

**Comment by jerodsanto** [comment]
I believe they are left blank and it lets postgres auth with the currently active user. You can see in the prod config we are using a url, which has the credentials in it.

**Comment by thenets** [comment]
@jerodsanto ah... make sense. I'll continue now and I'll try to finish it.

**Comment by thenets** [comment]
@jerodsanto How can I run one specific config file?
I just have the `mix phx.server` command. What's the default and main config file? I didn't found any doc or comment related to that.

**Comment by thenets** [comment]
Any ideia of what this error message mean?
I run the migrations, start the server and got this error:

![image](https://user-images.githubusercontent.com/2138276/35942685-97ba2b40-0c3d-11e8-8fa0-54383eed864c.png)

The commands can be found here:
https://github.com/thenets/changelog-docker/blob/master/entrypoint.sh#L12-L13

**Comment by jerodsanto** [comment]
Are you running in production mode? The `secret_key_base` is set in config.exs, but in prod config it reads it from environment variables.

**Comment by gerhard** [comment]
Superseded by #246
