### ISSUE TITLE
Make GitHub Recognize Repo as Elixir

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/changelog.com#121]
![2016-10-26 at 8 26 am](https://cloud.githubusercontent.com/assets/8212/19727656/ef610292-9b55-11e6-8ad1-5d2b2cc14dfa.png)

Like Thomas Jefferson once said,

> You either die a hero, or you live long enough to become a JavaScript app

It's pedantic, but I'd 💚  for this repo to be classified as Elixir. A few ways we can work toward this:

1. Un-vendor Semantic UI. There's a ton of JS/CSS in `web/static/semantic`. Someone with more webpack-fu than me can surely get this working inside the admin webpack pipeline.
2. Add tests. There's plenty of low hanging fruit (view functions for one) that I haven't written tests around. This would bolster our Elixir LOC.

Any other ideas on how to do this without drastic measures? We have a fair bit of Sass going on, so it might be tough...

**Comment by matiaskorhonen** [comment]
You could just exclude those files from [Linguist](https://github.com/github/linguist)'s analysis by using a `.gitattributes` file: https://github.com/github/linguist#using-gitattributes

**Comment by jerodsanto** [comment]
@matiaskorhonen YAS! I had no idea this was a thing.

**Comment by jerodsanto** [comment]
That's all it took @matiaskorhonen, thanks!

![2016-10-26 at 8 55 am](https://cloud.githubusercontent.com/assets/8212/19728714/11ead2e4-9b5a-11e6-8934-604ee568f59b.png)

**Comment by hoopyfrood** [comment]
TIL Amazeballs
