### ISSUE TITLE
Behavioral testing question

### ISSUE THREAD

**Issue by pdgonzalez872** [thechangelog/changelog.com#124]
First of all, thank you for making this open source, this is amazing.

This isn't an issue so please feel free to close this as soon as you need, but I have a question regarding  testing and was hoping to get in touch with you. I was wondering how you test the application flow and how things fit together as a whole. In Rails, one would use [Capybara](https://github.com/jnicklas/capybara) for these types of tests (seems like [Tuco-tuco](https://github.com/stuart/tuco_tuco) in the Elixir world?), but I don't think I saw these types of test in this repo.

What are your thoughts on this type of testing? Do you do these? If you do it in this repo, can you please point to where, because I think I missed it. These are the expensive tests (time wise) that test a feature end to end. If you don't do it, could you please share why?

Thank you so much for making this open source, this is an amazing learning opportunity for me and I bet for a lot of other people as well.

**Comment by jerodsanto** [comment]
Howdy, @pdgonzalez872! 

Great question, and no: you didn't miss it. We don't have these types of tests. I'm not philosophically opposed to behavior/integration tests (I use them often), but here are a few reasons why they don't exist as of today:

1. This app uses _very little_ JavaScript, so if my controllers respond appropriately (render correct html, redirect, etc) I have confidence that the app works as expected.
2. This app have _very few_ user-facing forms and workflows right now (this will change for sure). The only non-admin forms are to sign up for our newsletters and they post to Campaign Monitor anyhow. The admin is not exposed to anybody but a core group of us so I'm less concerned about things breaking there (again we have controller tests on the admin, but we're not driving the UI at all).
3. As you stated, full-stack tests are expensive in terms of compute time and complexity. I'm sure they'd be faster w/ Elixir, but in my experience as soon as you bring PhantomJS into the mix, it's tough sledding.

That being said, there are _many_ areas of the application that are untested and I'd gladly review/accept PRs that add these (or any) kind of tests.

Thanks for the kind words, it means a lot that people like yourself care enough to write in. 💚

**Comment by pdgonzalez872** [comment]
I agree with your points. We have lots of these acceptance/feature tests at work (a big Rails app) so I'm familiar with the tough sledding.

I'm being pulled into an Elixir project at work soon (am happy about it), so was curious about how people were handling these problems so thanks 
for the response.

Regarding PRs: I'll definitely try to put some up!

Closing this for now as you have answered my questions! 

Have a good one,

Paulo
