### ISSUE TITLE
Make post titles use h1 tag

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/changelog.com#130]
Just swapping the html element didn't quite do it. The styles will need to be adjusted to suit the h1 instead of the current h2.

**Comment by codyjames** [comment]
This was based on the episode#show view using the H2 for the post title. I assume we should adjust this in both places (and others I may find)?

**Comment by jerodsanto** [comment]
yes let's make it right everywhere that it makes sense.

**Comment by orendon** [comment]
is anyone working on this? if not I would be more than happy to do it

**Comment by jerodsanto** [comment]
@orendon go for it! @codyjames will provide feedback/help if you need it. 💥
