### ISSUE TITLE
Consistent timeline on embed

### ISSUE THREAD

**Issue by adamstac** [thechangelog/changelog.com#142]
I noticed today that the "played" vs "to be played" time on the timeline were different thickness's.

![screen shot 2016-12-05 at 3 42 23 pm](https://cloud.githubusercontent.com/assets/2933/20903662/d05bc686-bb01-11e6-9bb9-72efc1ceff3c.png)
They should both be the same thickness to keep the click/tap target the same.

**Comment by codyjames** [comment]
That looks grody.
