### ISSUE TITLE
Make check boxes on account page clickable

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/changelog.com#158]
This tripped up @ladyleet yesterday when she thought the "Request a Slack Invite" button was broken, but in reality it's not part of the link.
<img width="551" alt="2017-03-16 at 12 32 pm" src="https://cloud.githubusercontent.com/assets/8212/24010058/c791df26-0a44-11e7-98ba-1556ae234420.png">

**Comment by mavimo** [comment]
@codyjames @jerodsanto I think we can close it.

**Comment by jerodsanto** [comment]
Ahh yes, I thought the merge itself would've 👍
