### ISSUE TITLE
Master podcast link issues

### ISSUE THREAD

**Issue by plod** [thechangelog/changelog.com#165]
On https://changelog.com/master when you click subscribe it anchors to the jsparty podcast, and same when you click the share link. I am willy to fix this myself if it is possible. 

I am guessing it is because the most recent podcast was a jsparty one. But think when you click subscribe should link to master?

**Comment by jerodsanto** [comment]
Hmm yeah I think it's using the most recent episode to render that partial since it assumes an episode, but there are no "master" episodes so it uses that instead.

Please give it a crack! If you find it too difficult, holler at me or assign to me to fix it 💚
