### ISSUE TITLE
Player should save current time

### ISSUE THREAD

**Issue by montogeek** [thechangelog/changelog.com#169]
Hi!

Accidentally I had closed the page 3 times when listening to a podcast, unfortunately the player does not save current play time.

Would you accept a PR that adds this feature?

Thanks!

**Comment by jerodsanto** [comment]
@montogeek we absolutely want this feature! 

Implementation could get super messy depending on how we go about it (it would also have to play nice with #161 which we have planned but haven't started on).

How would you go about designing and implementing this feature?

(happy to hop on Skype or something to hash it out if you'd like)

💚

**Comment by agustif** [comment]
I couldn't find where the player is located in the code, but I immediately thought of VideoJS for this.

https://github.com/mercuryseries/track-videojs-play

**Comment by w3bdev1** [comment]
Until this feature is implemented, for the time being a [beforeunload event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) can be triggered, so that user will get a chance to confirm on leave.

**Comment by jerodsanto** [comment]
This is how it works now! ✊
