### ISSUE TITLE
Have admin panel in changelog.com?

### ISSUE THREAD

**Issue by vanloc0301** [thechangelog/changelog.com#170]
I tried with:

http://localhost:4000//admin

Seem not working.

**Comment by jerodsanto** [comment]
👋 @vanloc0301! 

That route requires authentication. If you ran the seeds you should have a couple admin users in your db. To sign in as one of them visit:

http://localhost:4000/in

and use `adam@stacoviak.com` as the email address. You should skip the email flow and have a button click to sign you in. After that, you can visit `/admin`.

💚

**Comment by vanloc0301** [comment]
I log in to http://localhost:4000/in.
A show like this:

![screenshot_2017-04-22_03-35-00](https://cloud.githubusercontent.com/assets/4168981/25295186/baa12e9a-270c-11e7-9a2d-3c4e07bb1734.png)

I clicked to line: ```Complete your profile (public profiles launching soon!)``` and change my email address to ```adam@stacoviak.com```.

Tried to log out and login again with this email.

I still can't visit ```/admin```

**Comment by jerodsanto** [comment]
@vanloc0301 it's not the email address that makes you an admin. There's an actual `admin` flag on the record in the `people` table. To fix you can open the database in `psql` (or some tool) and `update people set admin='t' where id=1` (assuming your record has an id of 1)

**Comment by vanloc0301** [comment]
Yes. I know. Thanks @jerodsanto 💯
