### ISSUE TITLE
GitHub signup asks for too many permissions

### ISSUE THREAD

**Issue by boneskull** [thechangelog/changelog.com#171]
Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/924465/25458863/85c06024-2a90-11e7-86b4-531aaea1be6f.png)

I couldn't figure out why changelog.com needed write access to all my repositories, so I backed out and signed up via Twitter instead. It may happily read my tweets.

:smile:

**Comment by adamstac** [comment]
I'm not sure of the details on the permissions, but this might be related reading -- which @zenorocha and I touch on in the next episode of The Changelog.

Why all these permissions? ~> https://github.com/dear-github/dear-github/issues/113

**Comment by zenorocha** [comment]
Yes! :/

**Comment by boneskull** [comment]
What is changelog.com actually doing that it would need repo access?

**Comment by jerodsanto** [comment]
We don't need repo access or mostly anything. We just have it set up wrong at the moment 😳

-Jerod
(sent on the go)

**Comment by adamstac** [comment]
I could be biased, but I really trust changelog.com — like, a lot.

**Comment by agustif** [comment]
It seems fairly easy to fix (Would you like a PR?)
At the end of https://github.com/ueberauth/ueberauth_github readme tells how to ask for specific permisssion scope.

## Calling

Depending on the configured url you can initial the request through:

    /auth/github

Or with options:

    /auth/github?scope=user,public_repo

By default the requested scope is "user,public\_repo". Scope can be configured either explicitly as a `scope` query value on the request path or in your configuration:

```elixir
config :ueberauth, Ueberauth,
  providers: [
    github: {Ueberauth.Strategy.Github, [default_scope: "user,public_repo,notifications"]}
  ]
```


If you let me know which permission you do want to ask for.

It seems looking at
    %{name: info.name, handle: info.nickname, github_handle: info.nickname}
That only general user info is looked upon, am I wrong?

maybe we can just ask for user, I could do a PR either with config or changing the Sign In path with the scope.

**Comment by jerodsanto** [comment]
@agustif a PR would be awesome! I think `user` scope is plenty. Let's put it in the config. Thanks! 💚

**Comment by agustif** [comment]
@jerodsanto I just did that https://github.com/thechangelog/changelog.com/pull/172

Cheers!

**Comment by agustif** [comment]
Added to config, I think it can be merged now.

**Comment by adamstac** [comment]
Just revoked changelog.com and reconnected GitHub. Here are the new permission being asked for GitHub auth.
![screen shot 2017-04-28 at 9 26 18 am](https://cloud.githubusercontent.com/assets/2933/25533035/e3cebb1a-2bf4-11e7-9cca-5cd471e72959.png)

**Comment by adamstac** [comment]
Thank you @boneskull for opening this issue and bring this to our attention! 💚

**Comment by adamstac** [comment]
Thank you @agustif for submitting the PR to correct this!! 💚 💚
