### ISSUE TITLE
Visual Issues with Globe Player

### ISSUE THREAD

**Issue by bnb** [thechangelog/changelog.com#173]
Opened the Live page earlier, and saw some graphical issues with the globe player.

Have had the live page open for a few hours - when I opened it I immediately noticed this, though, and it's persisted. It changes every ~minute or so (maybe a bit less) to another kind of visual glitch.

*Browser:* Chrome Latest
*Plugins:* Disconnect (Ad blocker). Hapeens when both disabled and enabled.

Screenshots: 
![pasted image at 2017_04_28 03_26 pm](https://cloud.githubusercontent.com/assets/502396/25544363/23620d3a-2c28-11e7-9c30-10e898cd24aa.png)
![pasted image at 2017_04_28 03_21 pm](https://cloud.githubusercontent.com/assets/502396/25544367/28b17a1e-2c28-11e7-967a-c38e8fcaaa2d.png)

**Comment by jerodsanto** [comment]
I've seen this a few times as well, but have no idea what's causing it. Appears to be Chrome only. @codyjames any ideas?

**Comment by codyjames** [comment]
That looks wonky. I can try and figure it out!

**Comment by codyjames** [comment]
@jerodsanto You still see this ever?

**Comment by jerodsanto** [comment]
@codyjames I haven't for a long time. A long time.

**Comment by bnb** [comment]
Feel free to close. I've not opened it up in a while, but will try to tune in again soon to see if it happens again - I can ping y'all if it does :)

**Comment by codyjames** [comment]
@bnb Sounds good. Thanks!
