### ISSUE TITLE
Volume Controls?

### ISSUE THREAD

**Issue by TheOdd** [thechangelog/changelog.com#174]
A couple days ago I found the Changelog podcast through Spotify and love it so far. I've only listened to it on my phone, but today I decided to listen while on my desktop through the online player. I usually turn the volume down on my browser because I have other applications up, etc. and I was looking for a place to lower the volume in the player. Unless I'm just blind, I don't see one. I did see some references to volume in both [audio.js](https://github.com/thechangelog/changelog.com/blob/baa356027250877cbf2792d0f63ab75df67b6949/web/static/app/components/audio.js) and [embedly.js](https://github.com/thechangelog/changelog.com/blob/e530391bad599537af55b2e1ad3d265416392a6a/web/static/app/components/embedly.js), but I feel like those are either stock values or deprecated at this point. If I'm missing something, please let me know, but otherwise I'd like to try and see if I (or anyone else) could get that implemented. I might not be able to as I'm relatively new to Elixir and just working with websites in general.

**Comment by jerodsanto** [comment]
👋 @TheOdd happy you found us! 

The volume controls in `audio.js` and `embedly.js` are there because Embedly requires them of us. So yeah, the underpinnings are there already.

The "hard" part of this feature (IMO) is the UI changes. I'd be down with hiding it behind keyboard shortcuts for now (like we did with playback speed in #143), but we'd still need some kind of indicator to show the current volume...

**Comment by TheOdd** [comment]
@jerodsanto Yeah, having the volume bound to some keyboard controls seems like a good placeholder/transition to the full UI feature being integrated. Not sure what your stance is on the balance between getting the function out there relatively quickly vs polish. To elaborate, I was wondering what your opinion was on having a pretty barebones indicator that isn't super polished, but it gets the job done. For example, some kind of indicator in the title tab for the page (like replacing the title with a volume icon and a percentage with the current volume) or something like that. Obviously, it would be something that is only there as a placeholder for a polished system/UI, but it would still be there on the site. Basically, would you prefer less pretty, more functional, and more frequent live changes to get the system going or would you want it in development for a bit and then come out once it's a bit more finished. I'm only asking because I'd want to know what to start on, either the barebones placeholder with core functions down or starting on figuring out a polished indicator. Sorry if I kind of repeated myself or rambled on, but I think I ended up getting my point across.

**Comment by jerodsanto** [comment]
Hmm, I did start down a "toast" branch awhile back that would allow for this style of interaction without a persistent UI, but I never finished it.

Ultimately, I would want @codyjames to style and polish the implementation, but if we can agree on this direction I will rebase that branch (I think it's a single commit) and you could play around with using it for current volume indication.

Here's what the rough version looks like when you change speed:

<img width="998" alt="2017-05-08 at 4 24 pm" src="https://cloud.githubusercontent.com/assets/8212/25826052/efcb8ec0-340a-11e7-8420-a203fa4b2081.png">

Thoughts on that direction @adamstac @codyjames? I could see other uses for this UI pattern, but I'm not 💯 on it quite yet...

**Comment by TheOdd** [comment]
Looks promising, I'm fine with whatever y'all agree on!

**Comment by codyjames** [comment]
This direction works for me! Very cool!

**Comment by jerodsanto** [comment]
Ok I pushed [that branch](https://github.com/thechangelog/changelog.com/tree/toast) so you can play around with it @TheOdd

**Comment by hamalaiv** [comment]
Can I ask why would it be hard to do the UI for this? In my opinion it could be similar to what you see in most of the video players. Something like this:

![changelog-volume-control](https://user-images.githubusercontent.com/9217370/28686130-e5a99b84-7312-11e7-8c14-0ab76d8d62a9.png)

On the bottom right I've added what the volume control would look like. The slider would come up on hover and on mobile the whole feature could be disabled.

**Comment by jerodsanto** [comment]
@hamalaiv I put "hard" in quotes for a reason. Not actually hard, but the main thing to get right. 😄 

I'm 👍 on this UI if @adamstac and @codyjames dig it

**Comment by TheOdd** [comment]
@jerodsanto So sorry I haven't been able to work on this. I've been at an amazing summer coding boot camp working with lots of JavaScript. Learned a bunch about MERN stack and should be able to do a lot more in general. In the near future, I'll try and take another look at this.

**Comment by jerodsanto** [comment]
@TheOdd no worries! Happy to hear you're enjoying the boot camp (and learning a lot)! 👏

**Comment by jerodsanto** [comment]
I think we can close this one now that there is at least a keyboard-based control for it thanks to #301
