### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by atefBB** [thechangelog/changelog.com#176]
Hey, My number one wish is to see `playlist` in your sounds player.
I want to see it soon!
And I'm thinking how to do it.
What about integrating AmplitudeJs (https://github.com/521dimensions/amplitudejs) in your website as a quick solution !?

**Comment by jerodsanto** [comment]
@atefBB we have plans for this, but it's probably not coming _real_ soon. Stay tuned! 

_(thanks for listening)_ 💚

**Comment by atefBB** [comment]
Should I work on it?!

**Comment by gerhard** [comment]
I am convinced that our views on this have changed since this was opened. If we still think that it's relevant, it's OK to re-open. In the interest of 2023 autumn cleaning this, closing now.
