### ISSUE TITLE
GitHub OAuth asks for write permission to User Profiles

### ISSUE THREAD

**Issue by LenPayne** [thechangelog/changelog.com#179]
Related to #171 which got merged back in April

The `user` [OAuth Scope](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/) by default gives both read and write access to user profiles.

The original change in #171 was to bump down from the default ueberauth scope `user,public_repo`, to simply `user`, but this still "Grants read/write access to profile info only."

It's the "write" access that is the issue. I'm sure The Changelog doesn't need to change my name or primary e-mail address. That would potentially allow an attacker to hijack GitHub accounts by rewriting emails and firing password recovery requests.

It's possible to change the scope to use either `user:email`, or simply no scope at all (which still gives read-only access to only public information, like username and public repos.)

I can make the one-line change (on [Line 44 of config.exs](https://github.com/thechangelog/changelog.com/blob/master/config/config.exs#L44)), but wanted to open the issue to discuss it before throwing a PR out.

Many other tools that authenticate with GitHub use either `[default_scope: 'user:email']` or just a blank scope: `[default_scope: '']`. Both give read-only access to public information like usernames, but `user:email` gives additional access to private e-mails, which may be useful for The Changelog.

**Comment by jerodsanto** [comment]
Good call, I thought we'd resolved this with the last one but looks like no. We do want `user:email`, but we don't need anything else. Happy to merge the PR 👍
