### ISSUE TITLE
Most of the links on the profile page are broken.

### ISSUE THREAD

**Issue by DamnedScholar** [thechangelog/changelog.com#182]
I've signed up for an account and was able to access almost everything, with the exception of the Slack invite link. I assume it's meant to be a link, because my cursor becomes a hand and it has an anchor tag, and the first item on that checklist does lead me to where I can edit my profile information. But the last three items all have hyperlinks to `thechangelog.com/~#`, and nothing is generated when I click on them.

Here's a gif of me trying to click on the Slack invite link a couple of times, then clicking on the profile edit link to demonstrate that it works.

https://puu.sh/xxtjI/2c9569a809.gif

**Comment by jerodsanto** [comment]
@DamnedScholar thanks for the report! This was a side-effect of our upgrade to Phoenix 1.3 that I didn't catch. Please try again now and let me know if it works for ya. 💚

**Comment by DamnedScholar** [comment]
Excellent, thank you. I just found the podcast and it looks like it fills a hole I've had in the tech-oriented side of my feed.
