### ISSUE TITLE
How does the slider move as you listen

### ISSUE THREAD

**Issue by gitleet** [thechangelog/changelog.com#184]
Hello,

Curious where in the code is the logic for the podcast player's slider to move as you listen to the podcast.
Is that a phoenix websocket thing?

**Comment by jerodsanto** [comment]
Howdy 👋

Our onsite player is an 'old-school' (jQuery era) JavaScript component that attaches to and manipulates the DOM in coordination with web audio API. Check out [audio.js](https://github.com/thechangelog/changelog.com/blob/master/assets/app/components/audio.js) and [onSitePlayer.js](https://github.com/thechangelog/changelog.com/blob/master/assets/app/components/onsitePlayer.js).

The specific part of the code that moves the slider is [line 219 of onSitePlayer.js](https://github.com/thechangelog/changelog.com/blob/cd740682aee8f5ad653fc825b092dcccf01c7e7a/assets/app/components/onsitePlayer.js#L219).

Does that help? Happy to explain in more detail if not.

**Comment by jerodsanto** [comment]
I _believe_ this question has been answered. Closing for cleanliness ✨
