### ISSUE TITLE
Could be useful to open the product roadmap too?

### ISSUE THREAD

**Issue by joebew42** [thechangelog/changelog.com#187]
Hi,

I am looking for some Elixir opensource projects to contribute in, and _changelog.com_ seems to be a very interesting project to dive in, but I can't find the _procuct roadmap_ in order to understand on which feature or stuff I can work on.

In the `README.md` I see:

> [...] Please remember that we have a product roadmap **in mind** so open an issue about the [...]

So I opened this issue to ask if is possible to publish the roadmap in way that it could be accessible to everyone who wants to contribute. Is it possibile? Do you think is a good idea?

Thank you in advance! :+1:

**Comment by jerodsanto** [comment]
@joebew42 this is something we've been pretty bad at, both internally and externally.

We're in the middle of a pretty significant overhaul (see v3 branch if you're interested), but after that gets launched we'll see about putting a public roadmap together.

Thanks for being interested in helping out! If you want to chat about what we're up to in real-time, come [hang out in our Slack](https://changelog.com/community). ✊

**Comment by jerodsanto** [comment]
Suggestion is under consideration, but not actionable at the moment so closing this issue for cleanliness' sake. ✨
