### ISSUE TITLE
Elixir Deployment

### ISSUE THREAD

**Issue by pdgonzalez872** [thechangelog/changelog.com#188]
@jerodsanto how are things? Hope everything is going great with you and your team!

I wasn't sure where to contact you about this but I've come across [gigalixir](https://www.gigalixir.com/) a couple of weeks ago through my good friend @costaraphael. I've heard a lot of questions about deploying Elixir/Phoenix apps, even [recently](https://www.reddit.com/r/elixir/comments/7pl5i7/how_did_you_learn_to_deploy_elixir_phoenix/). We paired on an sample app and got it deployed by following their docs. I wish more people would hear about this so that's why I decided to reach out to you guys.

Definitely a good resource that I wish more people knew about.

Thanks for your time! Keep rocking!

**Comment by pdgonzalez872** [comment]
Closing this as I believe you will get a notification regardless... Thanks!

**Comment by jerodsanto** [comment]
@pdgonzalez872 cool stuff, I plan on giving it a try on an upcoming side project. 🍻

**Comment by jerodsanto** [comment]
@pdgonzalez872 p.s. best place to send us links/projects/announcements is in our [Ping repo](https://github.com/thechangelog/ping/issues). ✊

**Comment by pdgonzalez872** [comment]
Awesome! Thanks for the tip. Will watch that repo too!
