### ISSUE TITLE
Form redirects with Turbolinks

### ISSUE THREAD

**Issue by adamwiggall** [thechangelog/changelog.com#190]
I'll start out by echoing others here and thank you immensely for making this project available. It's such a valuable learning resource, and I appreciate your generosity. 💚

My question is around your implementation of redirects following form submissions. As far as I can tell I've replicated what you have handling the forms, but I seem to be missing something on the redirects. Turbolinks is working as it should for the submissions, but the URL isn't updating to the resource in the `redirect` function from the controller.

In `app.js` I've used https://github.com/thechangelog/changelog.com/blob/6058c1a3074f1182a51c7ab947dcefecc75f15be/assets/app/app.js#L146-L171
but
https://github.com/thechangelog/changelog.com/blob/6058c1a3074f1182a51c7ab947dcefecc75f15be/assets/app/app.js#L161
is never evaluating to true.

I looked at the two links you have at the top of the plug https://github.com/thechangelog/changelog.com/blob/master/lib/changelog_web/plugs/turbolinks.ex and found that I got the same result from the first one (functional forms but not updating the URL), but had success with the second one https://gist.github.com/imranismail/5527b545f38b3be94579fc3b6d9f029e.

However, the one that works requires me to override `Phoenix.Controller` in `myapp_web.ex` and feels like too much. I see from the comments in the file you used that gist for inspiration, so I'm guessing you may have felt the same way?

It should also be noted that if I return a 200 from the plug, as you were doing until the last pull request on that file, https://github.com/thechangelog/changelog.com/commit/5855a949ae6c15a60470d362c2ae08408a1f7143#diff-ae1069e4f0a1ead22214a43474fdcf18 the URL updates, but, as noted in the commit message, I lose the flash, which I can't do.

So. Is there some code I'm missing? I've grepped all through the project, but I'm coming up short. 

Any help would be very much appreciated. Thanks in advance.

**Comment by LostKobrakai** [comment]
You can keep the 200 response if you move the turbolinks plug before phoenix's `fetch_flash`. This will result in the session data being saved before the turbolinks plug does change any 30x response to the 200.

**Comment by jerodsanto** [comment]
Yeah try what @LostKobrakai said. I'm not sure why it works w/ a 200 and not a 303 as it works for us with either one, but if plug order w/ a 200 works for you it might be time for me to follow @LostKobrakai's footsteps...

**Comment by adamwiggall** [comment]
Well, @LostKobrakai is right. Reordering the plugs works for me if I return a 200. Still not working with a 303.

**Comment by jerodsanto** [comment]
@LostKobrakai @adamwiggall ok y'all convinced me to change our implementation to rely upon plug order instead of browsers handling 303s correctly. ✊
