### ISSUE TITLE
Middle clicking on episode links on https://changelog.com/podcast both opens a new tab and navigates

### ISSUE THREAD

**Issue by hoelzro** [thechangelog/changelog.com#195]
Environment:

  * Arch Linux
  * Firefox 58

Steps to reproduce:

  * Navigate to https://changelog.com/podcast
  * Middle click on an episode link (the top one for me today is the devhints episode)
  * A new tab with the episode page is opened, and the current tab navigates to the episode page as well

Expected behavior:

  * The new tab should be opened, but the current tab should not navigate

Interestingly enough, I saw this on srcd's blog as well (see https://twitter.com/hoelzro/status/937732969623642112) - maybe there's some shared component you're using?

**Comment by jerodsanto** [comment]
@hoelzro thanks for the great bug report! I just deployed a change to how we handle those visits which should resolve your problem. Do you mind trying it and reporting back?

**Comment by hoelzro** [comment]
@jerodsanto Looks good, thanks!
