### ISSUE TITLE
PWA Support?

### ISSUE THREAD

**Issue by 108kb** [thechangelog/changelog.com#197]
Any ideas to implement PWA for changelog.com?

**Comment by filosofikode** [comment]
I mean for the news. Yeah I love it

**Comment by jerodsanto** [comment]
Definitely open to it, @filosofikode. What all does that imply and/or require?

**Comment by disjfa** [comment]
I see you use webpack for client side things, so the first step is using workbox (https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin)

I'll check if i get the site up and running locally, never worked with elixer.

**Comment by disjfa** [comment]
Also find that i dit it wrong 😄 ! Cache files are created with a hash using phx.digest.

More to read!

https://www.botsquad.com/2018/03/07/phoenix-sw/
