### ISSUE TITLE
Highlight linked paragraph in transcripts

### ISSUE THREAD

**Issue by FND** [thechangelog/changelog.com#199]
It's great that transcripts allow deep links, e.g. https://changelog.com/podcast/283#transcript-181
(Indeed, it's great that you provide transcripts in the first place!)

However, if you send someone to that URL, it's not immediately obvious what's being referenced (in part due to the fixed header overlapping the target, but that's a different issue).

Thus it'd be useful if the respective target paragraph was highlighted:
```sass
:target {
    background-color: $highlight;
}
```

> The :target CSS pseudo-class represents a unique element (the target element) with an id matching the URL's fragment.

https://developer.mozilla.org/en-US/docs/Web/CSS/:target

**Comment by jerodsanto** [comment]
Good idea (and great point on the nav overlapping the content)! This sounds like a job for @codyjames 

(unless you're interested in contributing it yourself, @FND 😄)

**Comment by codyjames** [comment]
Sounds good! I see another improvement related to this that I'd like to make as well (offset the anchor so the sticky nav doesn't block the target).

I'll let you know when this is up, @FND.

**Comment by FND** [comment]
Looking good - thanks for the impressively quick response!
