### ISSUE TITLE
RSS feed for the weekly

### ISSUE THREAD

**Issue by trevordmiller** [thechangelog/changelog.com#202]
I'm trying to subscribe to https://changelog.com/weekly via RSS. But it seems that the feeds available are either:
1) Everything
2) Individual items

An example using Feedly:

![image](https://user-images.githubusercontent.com/5497885/37007113-eeb72582-2098-11e8-9ded-2d6ca03cf26f.png)

Please add a feed for getting the weekly via RSS.

Thanks :)

**Comment by jerodsanto** [comment]
@trevordmiller this isn't on our short-term roadmap. In the meantime, maybe try [Kill the Newsletter](https://www.kill-the-newsletter.com) or a reader like [Feedbin](https://feedbin.com) that will sub to newsletters and convert them to feeds for you?

**Comment by trevordmiller** [comment]
Ok thanks

**Comment by tnguyen14** [comment]
@jerodsanto how do I find the newsletter on Feedbin? I can't seem to find it.

**Comment by jerodsanto** [comment]
@tnguyen14 it's in your account settings under Newsletters & Pages

<img width="462" alt="Screen Shot 2020-04-09 at 2 38 09 PM" src="https://user-images.githubusercontent.com/8212/78934015-cf885b80-7a6f-11ea-9c6e-d30c0a356b3f.png">

**Comment by tewe** [comment]
The **Weekly is now News**, a podcast whose show notes only link to web page with the actual show notes. That page does not have a feed, only an e-mail newsletter. So this **issue is still relevant**. Next Monday I'll now if Kill the Newsletter works.
