### ISSUE TITLE
Automate dependency updates

### ISSUE THREAD

**Issue by greysteil** [thechangelog/changelog.com#208]
Just listened to your pod with Rhys from Renovate and wondered if you'd be up for automating dependency updates for this repo.

I built [Dependabot](https://dependabot.com) to do that, and it works great with Elixir (we're a bit ahead of Renovate on that one, and on a bunch of other languages). I just ran it on [my fork](https://github.com/greysteil/changelog.com/pulls) and submitted [this PR](https://github.com/thechangelog/changelog.com/pull/207) from one of the branches it generated.

(I think he might have got the idea of [pooling test results](https://dependabot.com/compatibility-score) from us, too 😉, but I'm just glad Dependabot is making a difference!)

**Comment by greysteil** [comment]
Nice. If/when you do want to give it a try it's free, only takes a few seconds to set up (you just have to click through the install process [here](https://app.dependabot.com)), and will rate-limit you to 5 PRs a day (at most) until you're up-to-date. :octocat:

**Comment by greysteil** [comment]
FYI, I just added a "security updates only" option to Dependabot, which means you'll only get PRs to fix vulnerable dependencies (blog post [here](https://dependabot.com/blog/security-updates-only)). There aren't many Elixir vulnerabilities at the moment, and none that affect this repo, but might be worth switching on for future monitoring all the same?

**Comment by jerodsanto** [comment]
@greysteil cool, I signed us up and turned on security updates only. Not before it managed to open a few PRs, though! 😆
