### ISSUE TITLE
Connection problems accessing the podcast mp3s

### ISSUE THREAD

**Issue by hhrutter** [thechangelog/changelog.com#241]
I am located in Europe and I noticed some odd behaviour when trying to listen to old podcasts (eg. GoTime from 2016) in the browser (Chrome in my case). 

The webpage hangs after clicking the Play button with the spinning wheel over the play button - the stream loading indicator I guess. Most of the time everything's fine on the first or second retry so this may be a CDN issue.

Here are some measurements for an old episode on my first try and then the retry.
Take a look at `time_starttransfer` which is supposedly the time it takes for the first stream bytes to arrive at the client and also the delay until you can hear actual audio. Looks like if this number is high the webapp hangs:

```
Go-> ~: ./curlt.sh https://cdn.changelog.com/uploads/gotime/3/go-time-3.mp3
{
 "time_namelookup": 0.063539,
 "time_connect": 0.088739,
 "time_appconnect": 0.169664,
 "time_pretransfer": 0.169754,
 "time_redirect": 0.000000,
 "time_starttransfer": 56.815415,
 "time_total": 65.430712
}Go-> ~: ./curlt.sh https://cdn.changelog.com/uploads/gotime/3/go-time-3.mp3
{
 "time_namelookup": 0.130844,
 "time_connect": 0.155940,
 "time_appconnect": 0.234990,
 "time_pretransfer": 0.235088,
 "time_redirect": 0.000000,
 "time_starttransfer": 0.262869,
 "time_total": 7.330892
```
... whereas accessing a recent episode works fine on the spot:
```
Go-> ~: ./curlt.sh https://cdn.changelog.com/uploads/gotime/79/go-time-79.mp3
{
 "time_namelookup": 0.063169,
 "time_connect": 0.086161,
 "time_appconnect": 0.167980,
 "time_pretransfer": 0.168117,
 "time_redirect": 0.000000,
 "time_starttransfer": 0.194850,
 "time_total": 55.774680
```

**Comment by jerodsanto** [comment]
Thanks @hhrutter, this is useful. Would you mind sharing the public IP address you're making these requests from (share it in Slack if you'd prefer). Also, would you post your `curlt.sh` script here so we can run it from other locations?

**Comment by hhrutter** [comment]
Sure.
I am using `https://github.com/mat/dotfiles/blob/master/bin/curlt`
Will post my IP on slack.

**Comment by jerodsanto** [comment]
@hhrutter we've been working to improve this. Will you please do some more tests on your end and let us know if the experience is improved at all? 💚

**Comment by hhrutter** [comment]
OK. I get almost instant audio on all episodes new or old that I checked.
`time_starttransfer` is consistently below 1 second.
LGTM 💚
