### ISSUE TITLE
Unable to hear podcasts and also unable to download

### ISSUE THREAD

**Issue by YogeshDeveloper** [thechangelog/changelog.com#242]
When I play podcasts it loads indefinitely

![60](https://user-images.githubusercontent.com/22373075/41287659-1cb41678-6e61-11e8-843e-8690213e814e.png)

When I try to download the following error happens 
![error](https://user-images.githubusercontent.com/22373075/41287708-3bfc95d2-6e61-11e8-8b8b-9ca8456aa1be.png)

**Comment by jerodsanto** [comment]
Thanks for reporting this! Do you mind sharing the IP address that you're trying to download our mp3s from? If that is too sensitive, at least the city/country?

**Comment by YogeshDeveloper** [comment]
Me from India.

Yogesh-SP
+91-989-466-0876
spyogesh1994@gmail.com
Linkedin <https://www.linkedin.com/in/yogesh-sp-8503b878/> | Twitter
<https://twitter.com/tweetyoge> | Facebook
<https://www.facebook.com/spyogesh>

Believes in two proverbs
"Ideas come alive if you in believe them"
"Journey to thousand miles begins with a single step"

**Comment by jerodsanto** [comment]
@YogeshDeveloper we've been working to improve this. Will you please do some more tests on your end and let us know if the experience is improved at all? 💚

**Comment by YogeshDeveloper** [comment]
Yeah sure, I can. What are the tests you want me to do only download or anything else?

**Comment by YogeshDeveloper** [comment]
Yes, I am able to download now. Tested with two podcasts. It works fine. Thanks for considering the thing that I reported.

**Comment by jerodsanto** [comment]
Happy to hear it!

-Jerod
(sent on the go)
