### ISSUE TITLE
Changelog Weekly emails looking bad in Reeder

### ISSUE THREAD

**Issue by Bertg** [thechangelog/changelog.com#245]
I guess I'm still oldschool, using my RSS reader to get the "important" news in my life.
But I love my Feedbin / Reeder app combo. I even get my important newsletter delivered to it.

This works fine, except for Changelog Weekly emails. What a bummer!

![screen shot 2018-07-04 at 10 54 55](https://user-images.githubusercontent.com/1434/42267210-b6292852-7f78-11e8-8c0d-c6309772b700.png)

Not sure if I should open the ticket here, or contact support of Reeder app. But as my other newsletters look fine, I thought to give this a shot first.

**Comment by jerodsanto** [comment]
That sucks! As you know, [we're big fans of RSS and Feedbin as well](https://changelog.com/podcast/240). 😄

@benubois is this something we can work together to resolve?

**Comment by benubois** [comment]
Hi @jerodsanto,

Happy to look into it! Looks good in Feedbin, but Feedbin does a lot of HTML preprocessing that Reeder might not do.

![screen shot 2018-07-04 at 11 06 57 am](https://user-images.githubusercontent.com/133809/42390735-c7e1b700-8101-11e8-860a-f9644b308734.png)

Another option would be to offer an RSS feed! 😀

If you're using a CMS or other software tool to produce the newsletter, you're one XML template away from having this available.

**Comment by jerodsanto** [comment]
I mean, all the exact same content is available via RSS already anyhow...

https://changelog.com/feed

**Comment by benubois** [comment]
I've made an update so that the API will now use the same HTML preprocessing as the web. The end result is apps will get cleaner HTML and reduce the chances of breaking the layout.

![screen shot 2018-07-17 at 2 42 25 pm](https://user-images.githubusercontent.com/133809/42847170-fa54356a-89cf-11e8-8543-e72142e2e04a.png)

**Comment by Bertg** [comment]
That looks amazing! Great job!

**Comment by jerodsanto** [comment]
Thanks Ben! I think that's as far as we can take this one... 💚
