### ISSUE TITLE
[error] GenServer #PID<0.262.0> terminating ** (RuntimeError) Connect raised a KeyError error.

### ISSUE THREAD

**Issue by dalerka** [thechangelog/changelog.com#247]
Hi, I'm trying to run this app locally for learning purposes, but at the `mix ecto.setup` step I repeatedly get the following weird error:
```
[error] GenServer #PID<0.262.0> terminating
** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (elixir) lib/keyword.ex:377: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Changelog.Repo couldn't be created: an exception was raised:
    ** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

        (elixir) lib/keyword.ex:377: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
        (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
###### Environment: MX-Linux 17.1 (Debian 9 Stretch),  Elixir v1.6.6, Postgres v10.  

I tried to set the password for `postgres` user to _empty string_ manually (to match `createuser --superuser --no-password postgres` in the `script/setup` ), but it didn't help.

Can someone please point me in the right direction?

**Comment by jerodsanto** [comment]
Can you confirm that you have a `postgres` user that can connect to Postgres without a password? Try this from the command-line: `psql -U postgres` and report back.

Also, `mix ecto.setup` is an alias for 3 distinct tasks

1. `mix ecto.create`
2. `mix ecto.migrate`
3. `mix run priv/repo/seeds.exs`

Try running them one at a time and see which one you get the error on (probs the 1st one, but still worth trying)

**Comment by dalerka** [comment]
Not sure if this is the way to go, but I managed to `mix ecto.setup` and run this app successfully after adding these lines to `config/dev.exs` (under `adapter: Ecto.Adapters.Postgres`):
```
username: "postgres",
password: "postgres",
hostname: "localhost",
```
and setting the password for _postgres_ user back to _'postgres'_ (via `psql` shell)

Thank you guys for open sourcing this app! Hopefully this will help other newcomers to Phoenix newbies :)

**Comment by jerodsanto** [comment]
Hmm, yeah we're in the process of tweaking our dev setup to run inside Docker so it'll hopefully be easier to get up and running real soon! 🙏
