### ISSUE TITLE
Player inaccessible after being dismissed with escape key

### ISSUE THREAD

**Issue by RyanWillDev** [thechangelog/changelog.com#251]
When listening to an episode pressing the escape key pauses the audio and dismisses the player.

If the same episode is continued by pressing the play button under the episode description the episode continues where it left off but the player never reappears.

Selecting a different episode shows the player again.

![playerbug](https://user-images.githubusercontent.com/12587988/45782672-3f828700-bc29-11e8-962b-e69eccf1d258.gif)

I'd be happy to track this issue down and submit a PR for it.

**Comment by jerodsanto** [comment]
Sounds good to me! Start here: [onsitePlayer.js](https://github.com/thechangelog/changelog.com/blob/master/assets/app/modules/onsitePlayer.js)

**Comment by RyanWillDev** [comment]
Okay. I have the site running locally, but I don't see any episodes listed. Anything I need to do to get some to display?

**Comment by jerodsanto** [comment]
There is a seeds file, which will throw a bunch of dummy data in there. That being said, it might be stale/inadequate... (could probably use some help there as well). To run it:

```
mix run priv/repo/seeds.exs
```
