### ISSUE TITLE
Add a section for retired shows?

### ISSUE THREAD

**Issue by danielcompton** [thechangelog/changelog.com#253]
I was trying to find [Request For Commits](https://changelog.com/rfc), but because it has been retired it wasn't listed on https://changelog.com/podcasts. I had to Google for it, I couldn't find any links to it on the site (though maybe I was looking in the wrong place).

What do you think about adding a "Retired" section, either at the bottom of https://changelog.com/podcasts or in a separate page linked from there? Maybe I'm just not looking in the right places :)

**Comment by adamstac** [comment]
Thanks for sharing your thoughts @danielcompton. We're not really trying to advertise retired shows, but as you've found we do keep them accessible on the site. We just don't link to them from `/podcasts` anymore.

With that said, I could see adding a new link to the podcast section of the footer nav linking to a page with only retired shows on it. Still yet we only have two retired shows. RFC gets linked to in the show notes anytime we mention it on a podcast episode.
