### ISSUE TITLE
Podcast Title Byline in main feed links to podcast home instead of episode

### ISSUE THREAD

**Issue by simeydk** [thechangelog/changelog.com#254]
This issue relates to entries for podcast episodes on the main feed. The header line with the Podcast name and episode number links to the landing page of the Podcast, rather than the specific episode, whereas the episode title and avatar links to the specific episode. Given that the episode number is featured in the header as well, I would have expected that to link to the episode, too.

Is this behavior intentional?

![image](https://user-images.githubusercontent.com/13088589/46830662-994a1d00-cda1-11e8-8968-15bb708c866b.png)

**Comment by jerodsanto** [comment]
@simeydk it is, but I can see why that is confusing. That section of the news item is what we call the _source_, which is 'where this news item came from'. In the case of episode news items, the podcast itself is the source, not the episode.

**Comment by jerodsanto** [comment]
We may revisit this decision as we continue to iterate on the news item design, but I'll close this for now as there is no immediate action to be taken.

Thanks for the feedback! Usually I reply much faster, but it must've slipped through the cracks during Hacktoberfest where I was reviewing/merging > 300 PRs on our transcripts repo...
