### ISSUE TITLE
RSS Feed contains duplicate charset in Content-Type header (breaking some readers)

### ISSUE THREAD

**Issue by jeroenj** [thechangelog/changelog.com#265]
The `charset` attribute in the `Content-Type` header is duplicated causing some readers (at least [Miniflux](https://github.com/miniflux/miniflux/issues/297)) to get errors when trying to parse the feed. While this might be handled in there I think it would also be good to remove the option from the header. 🙇 

```
$ curl -I https://changelog.com/feed
HTTP/1.1 200 OK
Date: Tue, 11 Dec 2018 07:14:24 GMT
Content-Type: application/xml; charset=utf-8; charset=utf-8
Content-Length: 87431
Connection: keep-alive
server: Cowboy
cache-control: max-age=0, private, must-revalidate
x-request-id: 2lnjbpp64egbmk9ots00sjb2
Strict-Transport-Security: max-age=31536000; preload
```

**Comment by jerodsanto** [comment]
Good catch! This is a bug in an upstream library. I opened a PR to fix it there and also can work around it on our end in the meantime.

**Comment by jeroenj** [comment]
Cool. Thanks! 😄

**Comment by jerodsanto** [comment]
Fix deploying as we type 🚀
