### ISSUE TITLE
"Share" link is broken

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/changelog.com#267]
When I click "Share" I get a JS error:
`Uncaught TypeError: this.overlay.show is not a function`

![image 2018-12-17 at 8 16 58 am](https://user-images.githubusercontent.com/398230/50100043-59097f80-01d4-11e9-9c37-dea195c05249.png)

Env:
* macOS Mojave 10.14.2
* Brave (Shield down) version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

**Comment by jerodsanto** [comment]
Blech! Sorry about that, thanks for the report ✊

Fix deploying as we type...
