### ISSUE TITLE
Episode number links to wrong page

### ISSUE THREAD

**Issue by captbaritone** [thechangelog/changelog.com#271]
<img width="952" alt="screen shot 2019-01-08 at 2 38 03 pm" src="https://user-images.githubusercontent.com/162735/50863290-0d6d7000-1353-11e9-9df3-295c8273ca37.png">

If I click "The Changelog #328" on [this page](https://changelog.com/podcast) it takes me to `https://changelog.com/podcast` (the page I'm already on) instead of `https://changelog.com/podcast/328`, which is what I would have expected.

**Comment by codyjames** [comment]
@jerodsanto Thoughts on this? I agree that it's a bit confusing.

**Comment by jerodsanto** [comment]
I agree it's confusing. This is the 2nd report we've gotten. I think we consider it a bug and change the link destination.

**Comment by captbaritone** [comment]
Thanks for the quick turn around. Love being able to report these kinds of things on GitHub.
