### ISSUE TITLE
Broken rss feed? 

### ISSUE THREAD

**Issue by dpshelio** [thechangelog/changelog.com#273]
I've tried with a couple of tools to include your podcasts in my collection, but no luck.

For example, accessing to [the feed](https://changelog.com/podcast/feed) with the browser I get this error:
```
XML Parsing Error: unclosed CDATA section Location: https://changelog.com/podcast/feed Line Number 17160, Column 1:

^
```

**Comment by jerodsanto** [comment]
Funny you should mention that. I was _just_ working on some fixes and improvements to our feeds. Should be all good now, please try again: 

https://podba.se/validate/?url=https://changelog.com/podcast/feed

✊

**Comment by dpshelio** [comment]
Working now perfectly!! Thanks!!!
