### ISSUE TITLE
The sign-up email confirmation link expires way too quickly.

### ISSUE THREAD

**Issue by huyz** [thechangelog/changelog.com#276]
I'm trying to subscribe for the sixth time. But your email confirmation link expires after 30 minutes.  That's way too short.  Every time I get my new mail notification, it's been over 30 minutes.
Very frustrating for a simple act of subscribing.

**Comment by jerodsanto** [comment]
Good call. In most cases the email gets delivered immediately, so I didn't think 30 minutes would be a problem. That being said, there is no reason it should be this short. I'll change it to 24 hours. Fix incoming!
