### ISSUE TITLE
If you try to sign up with a profile image the magic link that is sent isn't MAY not valid

### ISSUE THREAD

**Issue by bongani-m** [thechangelog/changelog.com#287]
I was trying to signup and I try to use a image that was 800x800, the sign up process looked like it worked but the magic link sent failed. Signup worked by not uploading an image, and I was able to upload that same image to update my account

**Comment by jerodsanto** [comment]
Thanks for the report @bongani-m I'll look into this ✊

**Comment by gerhard** [comment]
In the interest of [Kaizen 7](https://shipit.show/70) (ships September 14), closing this now. If we still think that it's relevant, it's OK to re-open.

改善
