### ISSUE TITLE
is it ok email button?

### ISSUE THREAD

**Issue by AucT** [thechangelog/changelog.com#290]
I'm not a designer but this looks ugly. :P  
![email-button](https://user-images.githubusercontent.com/2072488/57979892-1e7a6c00-7a2c-11e9-9245-feacf557559b.JPG)

**Comment by codyjames** [comment]
Yeah, I think the button text is supposed to be white. Can you tell us what email client you are using so we can debug?

**Comment by AucT** [comment]
mail.google.com web version chrome 74.0.3729.157 on  win 10

**Comment by codyjames** [comment]
@AucT Thanks for the info!
