### ISSUE TITLE
Possible CDN issue

### ISSUE THREAD

**Issue by just1689** [thechangelog/changelog.com#294]
Good day

Tried to open https://changelog.com/podcast/347 online. It could not get the podcast.
Then tried from my podcast client on my phone - didn't work either.

Thought - hey I'll get the mp3. That didnt work either. Then I saw the url has 'cdn' in it. Decided to VPN into London (I'm physically in South Africa) and BOOM its working.

Only letting you know because it may be a problem for others too. Maybe tell your CDN provider?

**Comment by jerodsanto** [comment]
@just1689 thanks for the report! I'll open a ticket with our CDN 💚

**Comment by jerodsanto** [comment]
@just1689 spoke with Fastly and they requested that you run https://www.fastly-debug.com and then send in the text block. You can paste it publicly here if you don't care, or email it to me privately (jerod@changelog.com)

Thanks!

**Comment by just1689** [comment]
Just checked and today the podcast mp3 is loading so this might not be all that helpful.

ewogICJnZW9pcCI6IHsKICAgICJjaSI6ICJob25leWRldyIsCiAgICAic3QiOiAiR0wiLAogICAgImN0IjogInNvdXRoIGFmcmljYSIsCiAgICAiY28iOiAiQUYiLAogICAgImNfaXAiOiAiMTk3LjI0NS4yMTguNzkiLAogICAgImNfYXNuIjogIjExODQ1IiwKICAgICJjX2Fzbl9uYW1lIjogImRwYm9sIiwKICAgICJyX2lwIjogIjQxLjE5My4zLjEyNiIsCiAgICAicl9hc24iOiAiMTE4NDUiLAogICAgInJfYXNuX25hbWUiOiAiZHBib2wiLAogICAgInJfY2kiOiAic3RlbGxlbmJvc2NoIiwKICAgICJyX3N0IjogIldDIiwKICAgICJyX2N0IjogInNvdXRoIGFmcmljYSIsCiAgICAicl9jbyI6ICJBRiIKICB9LAogICJwb3BMYXRlbmN5IjogewogICAgImxociI6IDE4MSwKICAgICJsY3kiOiAxNzksCiAgICAiZnJhIjogMTk1LAogICAgImhobiI6IDE5MiwKICAgICJzaW4iOiAzNDEsCiAgICAiZmpyIjogMjg2LAogICAgImpuYiI6IDcsCiAgICAiY3B0IjogMjcsCiAgICAiYXRsIjogMjY0LAogICAgImFueSI6IDIzCiAgfSwKICAicG9wQXNzaWdubWVudHMiOiB7CiAgICAiYWMiOiAiY3B0IiwKICAgICJhcyI6ICJjcHQiCiAgfSwKICAicmVxdWVzdCI6IHsKICAgICJyZXNvbHZlcl9pcCI6ICI0MS4xOTMuMy4xMjYiLAogICAgInJlc29sdmVyX2FzX25hbWUiOiAiVm94LVRlbGVjb20sIFpBIiwKICAgICJyZXNvbHZlcl9hc19udW1iZXIiOiAiMTE4NDUiLAogICAgInJlc29sdmVyX2NvdW50cnlfY29kZSI6ICJaQSIsCiAgICAiY2xpZW50X2lwIjogIjE5Ny4yNDUuMjE4Ljc5IiwKICAgICJjbGllbnRfYXNfbmFtZSI6ICJWb3gtVGVsZWNvbSwgWkEiLAogICAgImNsaWVudF9hc19udW1iZXIiOiAiMTE4NDUiLAogICAgInRpbWUiOiAiMjAxOS0wNi0xNFQxNToxMjoxMC4wMDBaIiwKICAgICJob3N0IjogInd3dy5mYXN0bHktZGVidWcuY29tIiwKICAgICJhY2NlcHQiOiAidGV4dC9odG1sLGFwcGxpY2F0aW9uL3hodG1sK3htbCxhcHBsaWNhdGlvbi94bWw7cT0wLjksaW1hZ2Uvd2VicCxpbWFnZS9hcG5nLCovKjtxPTAuOCxhcHBsaWNhdGlvbi9zaWduZWQtZXhjaGFuZ2U7dj1iMyIsCiAgICAidXNlcmFnZW50IjogIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS83NC4wLjM3MjkuMTY5IFNhZmFyaS81MzcuMzYiLAogICAgImFjY2VwdGxhbmd1YWdlIjogImVuLVVTLGVuO3E9MC45LGFmO3E9MC44IiwKICAgICJhY2NlcHRlbmNvZGluZyI6ICJnemlwIiwKICAgICJmYXN0bHlzZXJ2ZXJpcCI6ICIxNTEuMTAxLjIyNC42NCIsCiAgICAieGZmIjogIjE5Ny4yNDUuMjE4Ljc5IiwKICAgICJkYXRhY2VudGVyIjogIkNQVCIsCiAgICAiYmFuZHdpZHRoX21icHMiOiAiMjQuNzAiLAogICAgImN3bmQiOiAxMjEsCiAgICAibmV4dGhvcCI6ICIxNzIuMjEuNDguMSIsCiAgICAicnR0IjogMjIuNjIsCiAgICAiZGVsdGFfcmV0cmFucyI6IDEyLAogICAgInRvdGFsX3JldHJhbnMiOiAxMgogIH0KfQ==
