### ISSUE TITLE
Add more cities in the Community Map

### ISSUE THREAD

**Issue by captn3m0** [thechangelog/changelog.com#296]
[The community map](https://cdn.changelog.com/images/content/community/map-7d214b8d534813e1e4636952cb6c9577.png?vsn=d) on the [/community](https://changelog.com/community) page doesn't cover:

- Any part of China
- No dots in India

I understand if it was generated from real data, but it doesn't feel inclusive.

India comprises 14% of all StackOverflow users, would be nice to get a dot :smile: 

Image for reference

![](https://cdn.changelog.com/images/content/community/map-7d214b8d534813e1e4636952cb6c9577.png?vsn=d)

**Comment by gerhard** [comment]
WDYT @jerodsanto, could we replace that map with a Plausible Analytics map screenshot? This is what the live demo one looks like: https://plausible.io/plausible.io

![image](https://user-images.githubusercontent.com/3342/186280481-feeb758f-395e-4ddb-ae7d-2a01fdb83b98.png)

While not perfect, it would be accurate.

The other, more time-consuming option would be to figure out what data we need to feed [Grafana Geomap](https://grafana.com/docs/grafana/latest/visualizations/geomap/). The added benefit is that we may be able to include a realtime view of our visitors.

**Comment by jerodsanto** [comment]
We decided to get rid of the community map altogether, rendering this issue moot.
