### ISSUE TITLE
Partial support for Google podcasts

### ISSUE THREAD

**Issue by Codereamp** [thechangelog/changelog.com#308]
Hi,
I noticed at least for one episode (Changelog 201) that the podcast is searchable in Google podcasts app and at podcasts.google.com with all meta information parsed and available, but the episode itself is not playable at both. Is this expected? 
The message when I click at the play button at the podcasts.google.com ([the podcast page](https://podcasts.google.com/?feed=aHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL1RoZUNoYW5nZWxvZy1PcGVuU291cmNlTW92ZXNGYXN0S2VlcFVw&episode=aHR0cDovLzVieTUudHYvY2hhbmdlbG9nLzIwMQ&ved=0CAMQzsICahcKEwjAxe7o-P3nAhUAAAAAHQAAAAAQCg) ) is

> Something went wrong
> This episode couldn’t be played. Please try again later.

**Comment by jerodsanto** [comment]
Hmm that is our old 5by5 feed. The new one on Google Podcasts [is here](https://podcasts.google.com/?feed=aHR0cHM6Ly9jaGFuZ2Vsb2cuY29tL3BvZGNhc3QvZmVlZA) (ugly URL 🙄 )

However, it only has our most recent 100 episodes, which is an RSS pagination feature we're using and doesn't seem to be well supported. I'm going to switch it back to the full feed soon, but haven't gotten around to it yet.

You can listen to that episode here, in the meantime: https://changelog.com/podcast/201

**Comment by jcs224** [comment]
Ha bummer, I suppose you had good reason to remove pagination but it was good testing ground for my podcast feed parser, which recursively went through the pages and created a JSON document of all the episodes. Now where will I test this feature? :laughing: 

https://www.npmjs.com/package/better-podcast-parser

**Comment by jerodsanto** [comment]
Yeah, not enough of the big podcast clients supported the feature for us to keep it around.

We had lots of complaints from folks who wanted to listen to an old episode and it wasn’t in our feed, so we went back to full feeds until pagination gains wider support.
