### ISSUE TITLE
Login error from  email link

### ISSUE THREAD

**Issue by tehdarthvid** [thechangelog/changelog.com#313]
Signed-up via email, filled the profile stuff.
Copy and pasted the link from the email to the browser and get the "Whoops" below.
Email link says I still have a day to use the link. Did this immediately after signing-up, not even 15 minutes.
Tried having another link sent, same result.
Also tried disabling various blockers.
Tried in Firefox, Chrome, Brave.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/2049325/77505963-8f39b280-6e9f-11ea-9354-b9093b3b714b.png">

**Comment by jerodsanto** [comment]
Hmmm that's a weird one. We show you as having signed in a couple minutes after account creation. The links are one-time use so my best guess is maybe for some reason your OS is visiting the URL during copy/paste? What happens when you click directly on the link in your email?

**Comment by tehdarthvid** [comment]
Got in! \(^^)/

It's likely the "links are one-time" part, should have thought of that case. I use Firefox Container Tabs, which I've setup to redirect to a specific container. It may have consumed the link then redirected to a separate container, which would need another login. Not realizing I've already consumed the one-time link, I kept trying the same link over and over, even when I tested in other browsers.

Thx! I'll keep this in mind next time. :)

**Comment by jerodsanto** [comment]
Glad we figured it out! Is there any way we could adjust the UX so this doesn't happen to folks in the future? (or at least lends them a hand if it does)

**Comment by tehdarthvid** [comment]
Maybe mention somewhere that the link is 1 time use. Doesn't have to be everywhere, but somewhere. Maybe somewhere near the "self-destruct" (brilliant, BTW, that's why I noticed the link lasts a day!) and the "already expired".

**Comment by tehdarthvid** [comment]
> Glad we figured it out! Is there any way we could adjust the UX so this doesn't happen to folks in the future? (or at least lends them a hand if it does)

Maybe mention somewhere that the link is 1 time use. Doesn't have to be everywhere, but somewhere. Maybe somewhere near the "self-destruct" (brilliant, BTW, that's why I noticed the link lasts a day!) and the "already expired".
