### ISSUE TITLE
Improve Compilation Performance

### ISSUE THREAD

**Issue by type1fool** [thechangelog/changelog.com#314]
## Problem
After watching Jerod's [thrilling adventure hour](https://www.youtube.com/watch?v=7UyETrdmLQA), it's clear the compiler is working way too hard, especially during recompilation. 220 files compiling on every hot reload will make your Macbook hot indeed.

## Solution
I'd like to see how much the tips below speed up the compilation process. It seems like converting imports to aliases will make the biggest difference.

I've forked and spun up the app locally. Before I get started, is there any reason _not_ to replace the imports with aliases?

## Resources
- [Speeding up re-compilation of Elixir projects](https://dashbit.co/blog/speeding-up-re-compilation-of-elixir-projects)
- [Understanding and fixing recompilation in Elixir projects](https://szajbus.dev/elixir/2020/04/14/understanding-and-fixing-recompilation-in-elixir-projects.html)
- [Mix Xref Docs](https://hexdocs.pm/mix/1.10.2/Mix.Tasks.Xref.html)

**Comment by jerodsanto** [comment]
Haha you felt my pain! 😭

This is a worthy endeavor, indeed. I can't think of any reason to switch imports to aliases. It's mostly ergonomics to me. Perhaps there might be scenarios where we have alias namespace clashes? Such as `Ecto.Query` vs `Changelog.Query` (this is not a thing but I think there are some cases where I mirror framework module naming conventions).

Please give it a shot and let me know what you find! 💚💚💚

(I'm also considering getting a dedicated streaming/recording machine so my laptop doesn't have to bear the entire burden. Compile times aren't really a problem for me in dev unless the machine is already under load from running other apps. But still!)

**Comment by type1fool** [comment]
Sweet.

That compiler pain is real. The new live layout stuff is a fresh learning curve, too. If there are alias conflicts, there's always full module names and `alias Changelog.Query, as: CLQuery`. I'll take a crack at this over the weekend.

FWIW, I just built a Ryzen 3700 Linux PC for dev stuff, and Elixir on 8 cores is amazing. Something like that would take at least the compiler load off the MacBook. My Air is still pretty slow at compiling even with no screen recording.

**Comment by jerodsanto** [comment]
Sounds good!

Btw I *just* recorded a video (uploading now) on [LiveDashboard](https://github.com/phoenixframework/phoenix_live_dashboard) and gave you a shout out as I was waiting for it to compile once again 😆

**Comment by type1fool** [comment]
This is the dependency graph for the project.

```bash
$ mix ref graph --format stats
Tracked files: 220 (nodes)
Compile dependencies: 474 (edges)
Structs dependencies: 114 (edges)
Runtime dependencies: 726 (edges)

Top 10 files with most outgoing dependencies:
  * lib/changelog_web/router.ex (47)
  * lib/changelog/schema/factory.ex (26)
  * lib/changelog_web/views/news_item_view.ex (23)
  * lib/changelog_web/controllers/admin/episode_controller.ex (22)
  * lib/changelog_web/views/layout_view.ex (20)
  * lib/changelog_web/views/episode_view.ex (17)
  * lib/changelog/schema/episode/episode.ex (17)
  * lib/changelog_web/views/admin/search_view.ex (16)
  * lib/changelog_web/views/admin/episode_view.ex (16)
  * lib/changelog_web/controllers/person_controller.ex (16)

Top 10 files with most incoming dependencies:
  * lib/changelog_web/router.ex (94)
  * lib/changelog/repo.ex (88)
  * lib/changelog_web.ex (87)
  * lib/changelog/schema/person.ex (65)
  * lib/changelog_web/helpers/shared_helpers.ex (48)
  * lib/changelog/schema/news/news_item.ex (47)
  * lib/changelog_web/plugs/conn.ex (41)
  * lib/changelog_web/plugs/response_cache.ex (40)
  * lib/changelog/schema/episode/episode.ex (39)
  * lib/changelog/hashid.ex (36)
```

This shows why there are 220 files recompiling on every live reload. Unfortunately, removing cross-module dependencies will not be a quick regex search-and-replace. 😫 So I'll be figuring out how best to tackle this over the coming days. Seems like there would be a semi-automated way to do this.

**Comment by nickjj** [comment]
@type1fool, you have a slight typo in that command, it's `mix xref graph --format stats`. Awesome command btw, thanks for mentioning it (I didn't know about it before).

**Comment by type1fool** [comment]
> @type1fool, you have a slight typo in that command, it's `mix xref graph --format stats`. Awesome command btw, thanks for mentioning it (I didn't know about it before).

Fixed. Thanks @nickjj.

**Comment by jerodsanto** [comment]
I'm super interested to see how this plays out. If it's an unadulterated win would it be fair to conclude 'imports considered harmful' for any non-trivial Elixir project?

**Comment by type1fool** [comment]
@jerodsanto It seems that way, but I have a new phx 1.5 project with `Router.Helpers` aliased, but other modules are imported. I don't fully understand the tradeoffs yet.

From [Speeding up re-compilation of Elixir projects](https://dashbit.co/blog/speeding-up-re-compilation-of-elixir-projects)
> Luckily, the Phoenix team is also well aware of the issues behind over-relying on compile-time dependencies. For this reason, Phoenix v1.4 eliminated two other sources of re-compilations in new Phoenix apps: router helper imports and plugs.

**Comment by wojtekmach** [comment]
Hi, I'm author of "Speeding up re-compilation of Elixir projects" and I'm sorry to hear your run into compilation slowness! 

As an exercise, I ran the import2alias script from the blog post for routes and cut down on some re-compilations, see: https://github.com/thechangelog/changelog.com/pull/315

before:

```
% touch lib/changelog/schema/episode/episode.ex  && mix compile 2>&1 | grep Compiling
Compiling 97 files (.ex)
```

after:

```
% touch lib/changelog/schema/episode/episode.ex  && mix compile 2>&1 | grep Compiling
Compiling 76 files (.ex)
```

(I also [fixed a bug in the script](https://gist.github.com/wojtekmach/4e04cbda82ba88af3f84c44ec746b7ca/revisions#diff-dc87c431dd834a73381a2f72fab7c0e7) that I found while running on your codebase!)

Unfortunately, the script can't automatically rewrite test files as they are not compiled by `mix compile` that the script is using. But it shouldn't be too hard to handle them too.

If you have modules like the ViewHelpers ones from the blog post, running the script on them might improve your project further.

> would it be fair to conclude 'imports considered harmful' for any non-trivial Elixir project?

> with Router.Helpers aliased, but other modules are imported.

It's not really about imports, it's rather about introducing compile-time dependencies on files that change often, if the file never changes we don't have to re-compile it! For example, changing `import Plug.Conn` to `alias Plug.Conn` won't be helpful because plug files will only change if you bump the version of the dependency. On the other hand, files in your project will change all the time. My rule of thumb would be to use imports _of your own_ code very judiciously.

**Comment by jerodsanto** [comment]
@wojtekmach thanks so much for hopping into the mix here* and helping out! 💚 

> My rule of thumb would be to use imports of your own code very judiciously.

This makes a lot of sense and was the conclusion I was coming to as I read through your post. We'll get your router PR merged and keep going down this path.

Cheers 🍻 

_(*pun unintended but enjoyable nonetheless 😉 )_

**Comment by type1fool** [comment]
@wojtekmach thank you for clarifying. I _knew_ I had seen a script somewhere.

**Comment by type1fool** [comment]
@wojtekmach After spending some time trying to convert the custom view helpers to aliases, I see that `.eex` files do not include columns in their metadata. Is that because [EEx options](https://hexdocs.pm/eex/EEx.html#module-options) don't include `:column`? If so, I'd be interested in whether a column option could be added to EEx.

Thanks again for the script and articles. This has been a fun rabbit hole. 🤯

**Comment by wojtekmach** [comment]
EEx was missing column information but we already added it (we briefly mention that in the article and that is going to be useful besides in the script). You'll have to use Elixir master or wait a few months for v1.11!

**Comment by type1fool** [comment]
## Bad News
Sorry I missed or forgot that section. I took your suggestion and installed Elixir 1.11.0-dev so `.eex` files would be traced.

When I ran the script, it mangled multiple piped function calls on the same line. 

BEFORE
```elixir
defp get(%{view_module: EpisodeView, episode: episode}),
    do: episode.summary |> md_to_text() |> truncate(320)
```

AFTER
```elixir
defp get(%{view_module: EpisodeView, episode: episode}),
    do: episode.summary |> SharedHelpers.mdSharedHelpers.truncate() |> truncate(320)
```

`SharedHelpers` should be prepended to both `md_to_text()` and `truncate(320)`. 

## Good News
So, I [updated the script](https://github.com/type1fool/changelog.com/blob/c314c4985e62a6423d1a69a42162674236ead780/lib_import2alias.ex#L40-L75) to iterate over the entries instead of the lines, and simplified the string manipulation using `String.replace/3`. Now the script handles single lines with multiple piped functions.

There were still two manual corrections I had to make. Once, `SharedHelpers.` was appended twice so some function was renamed to `SharedHelpers.SharedHelpers.some_function`. The other correction was due to `import ChangelogWeb.Helpers.SharedHelpers` being on a separate line from its `only [some_function/2, ...]`.

## Great News
With AdminHelpers, PublicHelpers, and SharedHelpers converted to aliases, the app only needs to recompile **47 files** when a view template is changed. There are still some modules (Meta) that can be aliased instead, and that should further reduce recompilation dependencies.

I'll work on that tomorrow. 🥱

**Comment by type1fool** [comment]
After aliasing `Meta` and removing the import of `Changelog.Plug.Conn`, the app only needs to recompile 5 files when a watched file is changed. That's a 98% reduction in recompilation. 🎅🏻

I ran mix test, and everything seems to be good. Thanks again to @jerodsanto for the live coding sesh, and thanks to @wojtekmach for the blog, the Elixir core improvements, and for kindly pointing out my oversights.

**Comment by wojtekmach** [comment]
> When I ran the script, it mangled multiple piped function calls on the same line.

Ah, of course. The script rewrites calls based on file:line:column, but if we have multiple things to rewrite in the given line, the column for the latter entries is outdated (we'd have to add an offset ( a negative one!) every time we've rewrote something.) Good catch!

String.replace/3 is definitely more straightforward to use. I actually originally used it but it gave wrong results with code like: `foo = foo()` and while a sufficiently robust regex would be fine I thought I'd try the column offset route. What we really want to is a [`Code.format_quoted/2`](https://github.com/elixir-lang/elixir/issues/9291#issuecomment-521598637) so that we change the imported call to an aliases one at the AST level where there is no ambiguity :)

> That's a 98% reduction in recompilation.

This is AWESOME.

**Comment by jerodsanto** [comment]
Improvements merged but maybe we leave this one open until the full story has been shared. Awesome work @type1fool!

**Comment by jerodsanto** [comment]
The blog post: [Slaying Changelog's compilation beast](https://changelog.com/posts/how-i-reduced-changelogs-compilation-dependencies-by-98)

And (BONUS!) the episode of Backstage: [YouTube made me do it](https://changelog.com/backstage/10)

I think we have thoroughly address this issue. Closing. 😆
