### ISSUE TITLE
Bug in embed link sent to interviewees

### ISSUE THREAD

**Issue by anjakefala** [thechangelog/changelog.com#320]
Hi!

I recently used the embed link you sent @saulpw to embed on our cite, and I found a small bug. 

You sent us

```
<audio data-theme="night" src="https://changelog.com/podcast/394/embed"
```

I needed to change it to

```
audio data-theme="night" data-src="https://changelog.com/podcast/394/embed"
```

because of these elements in `embed.js`.
```
r=t.getAttribute('data-src')
i=e.createElement('iframe');i.setAttribute('src',r+'?theme='+n+'&referrer='+e.location.href)
```

It was such a pleasant interview, I loved listening to it. ^^

**Comment by jerodsanto** [comment]
👋 @anjakefala I'm glad you enjoyed the episode (and thanks for sharing it around 💚)

Is it possible that the embed code got lost in translation somewhere? I double checked our mailer content just now and it looks like this:

<img width="943" alt="Screen Shot 2020-05-17 at 8 28 45 AM" src="https://user-images.githubusercontent.com/8212/82148308-098c1080-9819-11ea-9bb8-cc914198947d.png">

If not, is there any way you or Saul could send me the full content of the email he received?

Thanks! ✊

**Comment by anjakefala** [comment]
So strange! I will forward the email I received to `editors`.

**Comment by jerodsanto** [comment]
I definitely see the issue in the email you forwarded, but even logging in to our Campaign Monitor account (how we send transactional emails) and looking at the _exact_ email sent to Saul... it still has the `data-` in there.

I'm going to have to chalk this up to a fluke unless we get another report. Thanks for letting us know, though, and I'm glad you got it figured!
