### ISSUE TITLE
Filename of log prevents me from cloning repository

### ISSUE THREAD

**Issue by thojanssens** [thechangelog/changelog.com#321]
Hello

In directory **changelog.com/test/fixtures/logs/** there are filenames that contain the ":" character which prevent me from cloning the repo.

> error: invalid path 'test/fixtures/logs/2016-10-10/2016-10-10T18:00:00.000-tDYyAzw6i7wBr3cAAAAA.log'
> fatal: unable to checkout working tree

**Comment by jerodsanto** [comment]
Hmm I haven't seen this before. Are you cloning on Windows?

The reason those fixtures are named as such is they match how Fastly names the files when storing them in S3. I _believe_ we can rename these safely without losing any fidelity in our tests, but I'll have to take a closer look to be sure...

**Comment by thojanssens** [comment]
I'm using Windows. And `git clone` doesn't allow to exclude files or a folder unfortunately.

**Comment by sunndeath** [comment]
> I'm using Windows. And `git clone` doesn't allow to exclude files or a folder unfortunately.

Could you please test this advise? https://helpdeskgeek.com/how-to/how-to-fix-filename-is-too-long-issue-in-windows/
I think we deal with the "long filenames on windows" problem.

**Comment by thojanssens** [comment]
The filename is 48 characters... 😅 that's not long. The problem is the ":" character.

**Comment by bongani-m** [comment]
if you clone the repo through WSL it will work.
