### ISSUE TITLE
Transcript for Brain Science episode not referenced from website

### ISSUE THREAD

**Issue by jugglinmike** [thechangelog/changelog.com#336]
At the moment, [Changelog.com's page for Brain Science episode 32](https://changelog.com/brainscience/32) doesn't include a link to a transcript, although [the transcript is available in the relevant repository](https://github.com/thechangelog/transcripts/blob/master/brainscience/brain-science-32.md) (and has been since early November).

Thanks for the great show and for transcribing it!

**Comment by jerodsanto** [comment]
Thanks for the report @jugglinmike! We sync the site with the transcripts repo, but sometimes the webhook fails for various reasons and one slips through the cracks. I manually refreshed that episode and it's there now.

Enjoy 😄  https://changelog.com/brainscience/32

**Comment by jugglinmike** [comment]
Right on--thanks! Coincidentally, the speakers discussed the transcript itself during this episode. Might need to set `CI_IRONY=0` in the hook's configuration :)
