### ISSUE TITLE
Unable to subscribe to podcast

### ISSUE THREAD

**Issue by emmbee7806** [thechangelog/changelog.com#338]
Trying to subscribe to the go podcast but after entering my email address I just get an error message.

![Screenshot 2020-12-10 124804](https://user-images.githubusercontent.com/33358938/101809929-2c984d80-3ae6-11eb-8b84-2b80e03fa28d.png)

**Comment by jerodsanto** [comment]
Hmm that message is when you fail the captcha, but I thought we made it more useful in the case that you never even saw a captcha. 

Did you see a captcha or not?

-Jerod
(sent on the go)

**Comment by emmbee7806** [comment]
No, the captcha did not pop up

**Comment by emmbee7806** [comment]
Tried again now. Still same error. No, I don't have any ad blockers on my browser...

**Comment by jerodsanto** [comment]
Lame, sorry about this! I did notice that I hadn't updated the error message on `/subscribe` like I did for `/join`, so I just pushed a fix for that so at least it shouldn't report a Styx line back at you now.

If it's not a script blocker... I use a hidden captcha so maybe it's getting caught by your pop-up blocker? 

If that's not the case would you mind opening your dev console and see if there are any errors or warnings in there?

Thanks!

**Comment by emmbee7806** [comment]
Don't have ad blockers and I didn't get any errors reported to the console.

**Comment by emmbee7806** [comment]
But I do remember seeing a warning about a handler taking too long. I'll recheck tomorrow.

**Comment by emmbee7806** [comment]
Clearing the cache and reloading did the trick. Was finally able to subscribe.

**Comment by jerodsanto** [comment]
Sorry you had so much trouble, but glad we got you onboard eventually! 👏
