### ISSUE TITLE
The site header repaints constantly

### ISSUE THREAD

**Issue by gpakosz** [thechangelog/changelog.com#343]
Hello,

The changelog.com uses a lot of CPU, without even playing audio.

Here's a screenshot of Activity Monitor on macOS for which the PIDs wasting CPU are those of 2 tabs being open on the changelog.com

![image](https://user-images.githubusercontent.com/553208/103405483-9b9e1a80-4b57-11eb-9204-f4f5c91b35fe.png)

I briefly used Chrome Devtools which show that the header is constantly repainting:
![image](https://user-images.githubusercontent.com/553208/103405506-b07aae00-4b57-11eb-93dd-560373c7a9b6.png)

I mostly tracked it down to CSS animations:
- the "Changelog++" animated rainbow link
- the hidden pulsating live indicator

But even when disabling all the CSS animations, the header still repaints every 15ms. This is a 1680 x 65 area being repainted every 15ms for no real reason and that impacts battery life.

Hope you can fix it!

**Comment by gerhard** [comment]
WDYT @jerodsanto?

**Comment by jerodsanto** [comment]
It was the animation on the Changelog++ link. I removed it and everything looks peachy.

<img width="1624" alt="Screen Shot 2022-08-30 at 3 19 56 PM" src="https://user-images.githubusercontent.com/8212/187535278-6af2a5f0-553d-4d50-9be1-ba25e18ccfa5.png">

What's odd is that we're still using `linear-gradient` in the CSS so the effect still looks the same, even without the animation in there...
