### ISSUE TITLE
Episodes

### ISSUE THREAD

**Issue by jonathandturner** [thechangelog/changelog.com#349]
Hi all, slight correction. I'm on two episodes of the Changelog:

https://changelog.com/podcast/152
and
https://changelog.com/podcast/363

https://changelog.com/person/jntrnr/podcasts

Cheers

**Comment by jerodsanto** [comment]
Hey Jonathan! Long time no talk. I do see both of your podcast appearances listed on your profile page. 

<img width="585" alt="Screen Shot 2021-01-18 at 8 29 24 AM" src="https://user-images.githubusercontent.com/8212/104927620-46d80d80-5967-11eb-9f62-a95dfce64d41.png">

Am I misunderstanding your correction or did someone fix it overnight and not follow up here about it?

**Comment by adamstac** [comment]
Yup. Someone fixed it overnight and didn't follow up _yet_ :)

Glad to get that updated for you @jonathandturner 🍻

**Comment by jonathandturner** [comment]
That was quick! Glad to see you both doing well. :relaxed:
