### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by porjo** [thechangelog/changelog.com#353]
Attempting to fetch an RSS feed with Javascript from a browser results in this error (Firefox):

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://changelog.com/gotime/feed?_=1612908014223. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Can header `Access-Control-Allow-Origin: *` be included for RSS feeds?

**Comment by jerodsanto** [comment]
Hmm well I thought this was an easy header addition to our feeds controller, but our in-memory cache isn't persisting header info so it's only there for the first request, then disappears once it's served from caching.

Digging deeper to fix this scenario...

**Comment by jerodsanto** [comment]
Should be good now!

<img width="600" alt="Screen Shot 2021-02-10 at 8 10 17 AM" src="https://user-images.githubusercontent.com/8212/107520846-74cffc80-6b77-11eb-91b8-849c756d3d80.png">

I'd love to hear what you're building with this 😎

**Comment by porjo** [comment]
Thanks, works for me. I'm calling it from here https://porjo.github.io/freshtube/ - originally designed for Youtube, and later extended to load RSS feeds.

**Comment by porjo** [comment]
This issue is happening again (not sure when it started, I just noticed):

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gotime.fm/rss?_=1680311144217. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 302.
```

I'm accessing it from the same place as last time: https://porjo.github.io/freshtube/ 

@jerodsanto fyi

**Comment by porjo** [comment]
Only closer inspection, only the initial URL gotime.fm is missing the CORS header. It redirects to  https://changelog.com/gotime/feed which does return the CORS header.

**Comment by jerodsanto** [comment]
Yeah all of our `.fm` domains are simple redirects to where the actual content lives on `changelog.com`
