### ISSUE TITLE
RSS Master feed not wellformed

### ISSUE THREAD

**Issue by ullgren** [thechangelog/changelog.com#354]
Error started this morning (CET) 

```
XML Parsing Error: not well-formed
Location: https://changelog.com/master/feed
Line Number 112, Column 107:
      <podcast:person img="https://secure.gravatar.com/avatar/4c3992e1cd245d47c58879eb44d341c4.jpg?s=600&d=mm" href="/person/shortdiv">Divya</podcast:person>
```
How to recreate: Get the master RSS feed (https://changelog.com/master/feed) and validate the XML.

Cause: The ampersand in the img URL is treated like an entityref. Should probably be encoded as `&amp;`

**Comment by jerodsanto** [comment]
Sorry about that, just added those new elements yesterday and forgot to esacpe the img urls! Should be fixed now ✊
