### ISSUE TITLE
Ship It! feed contains XML error

### ISSUE THREAD

**Issue by kraai** [thechangelog/changelog.com#370]
When I visit https://changelog.com/shipit/feed in Chromium, it displays the following error:

```
This page contains the following errors:

error on line 16 at column 388: xmlParseEntityRef: no name
```

I think that this is caused by an unescaped ampersand in the description.  I think this also prevents the feed from being parsed by AntennaPod, which prevents me from subscribing.

**Comment by kraai** [comment]
It might be sufficient to add `|> escaped()` after `Map.get(@podcast, :extended_description, "")` to two places in `lib/changelog_web/templates/feed/podcast.xml.eex`, but I haven't tested it.

**Comment by kraai** [comment]
It might be sufficient to add `|> escaped()` after `Map.get(@podcast, :extended_description, "")` to two places in `lib/changelog_web/templates/feed/podcast.xml.eex`, but I haven't tested it.

**Comment by kraai** [comment]
It might be sufficient to add `|> escaped()` after `Map.get(@podcast, :extended_description, "")` to two places in `lib/changelog_web/templates/feed/podcast.xml.eex`, but I haven't tested it.

**Comment by jerodsanto** [comment]
Good call! Should be all fixed now! ✊
