### ISSUE TITLE
Possible Fix for Speeding up Mac Docker Latency

### ISSUE THREAD

**Issue by bongani-m** [thechangelog/changelog.com#371]
Based off of[ this comment ](https://github.com/docker/for-mac/issues/3497#issuecomment-846259937): 
> If you are sharing the folder between host and VM then FS performance will probably not be fast. See if things improve if you don’t use shared folders

I notice that removing the most of the folders that are shared and copying the relevant folders when rebuilding the `thechangelog/runtime` image got rid of any latency. I realize that it may not be useful because it would require rebuilding the runtime image every time a change is made, but it did speed things up.

**Comment by gerhard** [comment]
Thank you for this @bongani-m.

After years of being on the fence with this, it's time to call it what it is and move away from this completely. This comment has more context https://github.com/thechangelog/changelog.com/issues/324#issuecomment-1224976158.

Closing as we are unlikely to address this, and instead remove the problem by removing all traces of Docker from this repo.
