### ISSUE TITLE
Magic link not working 

### ISSUE THREAD

**Issue by ea-michael** [thechangelog/changelog.com#375]
I have a ChangeLog++ subscription and I'm able to log and view my subscription fine. When I try to log into the community, I receive the magic link and when I click it a get a woops on the page. I created a second account with another email and when I get the magic link it works fine and logs me in. The only difference between the emails is one that is not working has periods in it, its starts with "m.j.".

**Comment by jerodsanto** [comment]
Sounds like a bug to me. Are you open to emailing me (jerod@changelog.com) the two email addresses you're using so I can take a closer look?

**Comment by gerhard** [comment]
In the interest of [Kaizen 7](https://shipit.show/70) (ships September 14), closing this now. If we still think that it's relevant, it's OK to re-open.

改善
