### ISSUE TITLE
Why do some mp3 requests take 60s or more, while others complete quicker?

### ISSUE THREAD

**Issue by displague** [thechangelog/changelog.com#383]
This started as a follow-up to [Ship It #18](https://changelog.com/shipit/18), and we (+@rawkode +@gerhard) tried to understand the difference in response times & types between various requests in [Live Debugging the Changelog's Production Kubernetes | Rawkode Live](https://www.youtube.com/watch?v=7zmRhHd-ohk). As all good investigations, this one created more questions:

* CDN cache hits vs misses
* 200 vs 206 (byte ranged) responses 
* HTTP vs HTTP2 clients
* geographic location
* application scope during mp3 requests (is this Phoenix/Elixir)?

Which observability tooling may help us identify the root cause for this? Is it the front end (ingress-nginx), back end (Elixir) or infra (e.g. local disk)?

---

### Follow-up items
- [x] @gerhard to integrate Honeycomb with ingress-nginx
- [ ] @gerhard to version and share dashboard used for the slides
- [ ] ?

**Comment by jerodsanto** [comment]
All mp3s are now served from S3 (with Fastly in front) so I believe this issue is no longer relevant. Should we close it, @gerhard?

**Comment by gerhard** [comment]
The answer is that some clients are slow, like Apple Watches, so they take longer to download mp3 files. It's also related to the variable speed of internet around the world, but unlike the first fast, this is more of an educated guess.

Closing 👍🏻
