### ISSUE TITLE
Link to Scribe URLs instead of Medium in News?

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/changelog.com#392]
Now that [Scribe](https://scribe.rip) exists, it might be cool to link to it as a frontend for Medium posts.

More info here: https://changelog.com/news/an-alternative-frontend-to-medium-LpQ4

#### Pros

- Better reading experience
- No Medium sign up spam

#### Cons/Questions

- What if Scribe goes away for some reason? Would we even know? Or would our links just start to 404?
- What if authors are trying to build a Medium-based following? Are we betraying their intent?

**Comment by gerhard** [comment]
Do you still want to look into this @jerodsanto in 2022?

If not, I am all for closing it and maybe re-opening when you feel like it.

**Comment by jerodsanto** [comment]
I think it's something we should do, but not high priority. I added the `help-wanted` label so I'd rather leave it open so people can see it.
