### ISSUE TITLE
newsletter links-proxy encodes special urls with html instead of percent-based

### ISSUE THREAD

**Issue by dym-sh** [thechangelog/changelog.com#394]
example (of https://changelog.com/news/its-all-gravy-53Pa )

> `https://email.changelog.com/t/t-i-cddnly-qduttcki-nd/`

- current: => `https://chris.manson.ie/it&#39;s-all-gravy`
- supposed: => `https://chris.manson.ie/it%27s-all-gravy/`

**Comment by jerodsanto** [comment]
Thanks for the report! This has something to do with how `Phoenix.HTML.Link.link/2`processes our news item links when we send them to it in our news issue templates:

https://github.com/thechangelog/changelog.com/blob/fb661d0cf3a4db731d46ef7f1cec44a5d1f4581a/lib/changelog_web/templates/news_issue/_item.html.eex#L6

Not sure what/if anything we can do about it as a user of that API, but happy to learn!

**Comment by dym-sh** [comment]
make different pipeline for email links :shrug:?

**Comment by gerhard** [comment]
Do we still want to keep this issue pinned @jerodsanto?

**Comment by gerhard** [comment]
Is this still relevant @jerodsanto?

**Comment by jerodsanto** [comment]
It's still a bug that hasn't been fixed, if that's what you mean by relevant?

**Comment by jerodsanto** [comment]
This one is no longer relevant because we aren't proxying newsletter links anymore. Direct links FTW!
