### ISSUE TITLE
Accidentally broke account by setting same email as other account

### ISSUE THREAD

**Issue by soumya92** [thechangelog/changelog.com#408]
I switched email addresses, and instead of signing in with my old address and then changing the email, I accidentally created a second account with my new address.

Hoping to undo that, I signed in with my old address and changed the email there, and now I can't sign in at all :disappointed: 

There should be some check that prevents you from changing the email address to one that's already associated with another account. Even better if it offered ability to merge accounts, but at least preventing me from being locked out would be a good start.

**Comment by jerodsanto** [comment]
Yo! Hmm I definitely think we won't let you change your email address to one that's already in the system. But I'll check in to it! Would you mind posting both addresses here? If not, you can email them to jerod@changelog.com and I'll take it from there.

**Comment by soumya92** [comment]
Emailed the details

**Comment by soumya92** [comment]
Discussed offline, this is fixed for me now.
