### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID for frontend assets after `./start_dev_stack up` finishes

### ISSUE THREAD

**Issue by Nezteb** [thechangelog/changelog.com#412]
I cloned the repo, ran `./start_dev_stack up`, waited, and once I saw that webpack had finished compiling I visit `localhost:4000` to see this:

<img width="841" alt="Screen Shot 2022-04-29 at 8 58 52 PM" src="https://user-images.githubusercontent.com/3588798/166086271-9ab907d5-9894-4b6d-a1ac-dd1f327c6690.png">

In the console there are a bunch of failed asset requests like so:
```
...
GET https://localhost:4001/static/css/app.css net::ERR_CERT_AUTHORITY_INVALID
...
GET https://localhost:4001/static/js/app.js net::ERR_CERT_AUTHORITY_INVALID
...
```

I'm not sure why the HTTP page is trying to pull assets from the HTTPS page.

The HTTPS (`localhost:4001`) page doesn't even return a response, and the Docker logs show this when trying to open it:
```
[info] TLS :server: In state :hello at tls_record.erl:558 generated SERVER ALERT: Fatal - Unexpected Message
```

I've combed the `README.md`. `mix.exs`, and can't find any mention of other commands I should be running.

Am I missing something? 🤔 

macOS: 12.3.1
Docker Desktop: 4.7.1

**Comment by jerodsanto** [comment]
Hmm I don't use the Docker setup so I'm not _super_ familiar with it, but it is setting `HTTPS: 'true'` in `dev_docker/changelog.yml`, which runs this code on `config/dev.exs`:

```elixir
if System.get_env("HTTPS") do
  config :changelog, ChangelogWeb.Endpoint,
    https: [
      port: 4001,
      cipher_suite: :strong,
      certfile: "priv/cert/selfsigned.pem",
      keyfile: "priv/cert/selfsigned_key.pem"
    ]
end
```

You can generate the self-signed cert by running `mix phx.gen.cert`. 

Give that a shot and let me know how it goes!

**Comment by Nezteb** [comment]
I tried that as well but then realized that the Docker Compose file takes care of that step for us: https://github.com/thechangelog/changelog.com/blob/master/dev_docker/changelog.yml#L13

In both cases it doesn't work for me. 🤔
