### ISSUE TITLE
IPv4-only S3 endpoint is used for post pictures

### ISSUE THREAD

**Issue by tambry** [thechangelog/changelog.com#419]
[This post](https://changelog.com/posts/thank-a-maintainer-on-us) uses the S3 endpoint `changelog-assets.s3.us-east-1.amazonaws.com`, which is IPv4-only. `changelog-assets.s3.dualstack.us-east-1.amazonaws.com` should be used instead to support both IPv4 and IPv6.

**Comment by gerhard** [comment]
I am thinking of fixing this sytem-wide @jerodsanto via:
1. backup db
2. search & replace
3. restore from the updated db backup

WDYT?

**Comment by jerodsanto** [comment]
@gerhard I'd challenge you to do the "search" part of this and see if there's even any S3 URLs left...

**Comment by tambry** [comment]
The blog post linked in the original issue is still using S3 URLs.

**Comment by jerodsanto** [comment]
All posts have now been updated to use cdn.changelog.com

**Comment by gerhard** [comment]
@jerodsanto I found `8` occurrences in the Dec. 27, 2023 backup:

<img width="1518" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/ececda27-a27d-445f-8826-f74ba562fbc1">

**Comment by tambry** [comment]
Just as an example, the link for "Urgency Importance Matrix" in [this post](https://changelog.com/jsparty/187) is indeed to a non-dualstack endpoint. Ditto the picture at the bottom [here](https://changelog.com/podcast/391). Presumably all those occurences are references within content itself.

**Comment by jerodsanto** [comment]
Ahh ok those are episode show notes not posts. I'll sweep through those and update them as well.

**Comment by jerodsanto** [comment]
ok sniped off those last 8 references 🎯
