### ISSUE TITLE
nightly.changelog.com doesn't support IPv6

### ISSUE THREAD

**Issue by tambry** [thechangelog/changelog.com#420]
It has no AAAA records.
```
root@tambre:~# dig nightly.changelog.com +short AAAA
root@tambre:~#
```
Enabling IPv6 on DigitalOcean instances after creation is a bit cumbersome and requires shutting them down for a few minutes, but can be done. Or at least that's how it was a few years ago.

**Comment by gerhard** [comment]
Finally solved by https://github.com/thechangelog/nightly/pull/42 via https://github.com/thechangelog/changelog.com/discussions/480 ✅
