### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by AustinGil** [thechangelog/changelog.com#422]
I've tried logging in twice today, but the email with the magic link never arrives to my inbox. I checked the spam folder as well. I'm using Gmail, if that matters.

**Comment by gerhard** [comment]
I just tried logging in with my email address and I received the magic link. Also using Google Mail.

I also tried GitHub login, which also worked. Same for Twitter.

Can you try again?

**Comment by AustinGil** [comment]
Yeah, I think this was a false flag. The emails took about 30min to arrive, but they did eventually come and I could log in.
