### ISSUE TITLE
Upgrade Elixir from 1.13 to 1.14

### ISSUE THREAD

**Issue by Nezteb** [thechangelog/changelog.com#427]
Similar to https://github.com/thechangelog/changelog.com/pull/423

[It's been exactly one month since Elixir 1.14 was released; time flies!](https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/)

At my workplace I recently upgraded us from 1.12 to 1.14 and it was pretty dang easy, so I'd like to whip up a quick PR for that. Once you've used the new `dbg` module you will never want to go back to `IO.inspect`. 😄

**Comment by ZhouMeng1998** [comment]
？

**Comment by gerhard** [comment]
Solved via https://github.com/thechangelog/changelog.com/pull/428

Thank you very much Noah! 🙌
