### ISSUE TITLE
Tried to join the changelog community. Failed due to non-existent captcha

### ISSUE THREAD

**Issue by ApolonTorq** [thechangelog/changelog.com#445]
An attempt to register shows this:
CAPTCHA fail. Are you blocking scripts? Are you a robot? 🤖

However, no CAPTCHA was presented, I'm not blocking scripts and am not a robot.

**Comment by ApolonTorq** [comment]
FYI: It worked today when attempting to do the same again.

**Comment by gerhard** [comment]
Glad that it worked @ApolonTorq! If anyone else hits this issue, please re-open.
