### ISSUE TITLE
Can't sign-up

### ISSUE THREAD

**Issue by spb2021** [thechangelog/changelog.com#461]
Hi,

Your sign-up page has room for improvement 😎

1) Firstly, whatever I try I cannot get past the CAPTCHA check

![image](https://user-images.githubusercontent.com/80110602/235450252-65a72a3a-8dce-47db-aabb-9c9ea8a461a8.png)

I am using iPhone Safari on IOS 16.4.1

I even reduced my security by enabling pop-ups but that didn't work even after I restarted Safari on my iPhone from scratch

2) if a user restarts safari after they encounter an error, it only remembers *some* of the entered items, even if it does remember the URL.  That maybe a feature of Safari security so could be outside your control.  Luckily I took a screenshot before I did it so I didn't have to relook up all my IDs again 🥳

3) the username (I think that's what the field is called, but it's a pain to go back and look whilst this form is being entered into) only accepts lower case letters (hmm Linux server at the back end methinks) so it would be useful to put a comment saying that somewhere where it will be noticed when entering the first time, rather than waiting for the error message.   Also, one could run a nifty script to automatically convert the username to lower case, and provide an info message saying that, or automatically map to lower case in your IAM.

4) Whenever an error occurs, you deleted the data in the field for the Avatar image. Meaning new users, have to faff around finding their image again from their extensive photo library (I moved it to a handy Album called Avatars at the third attempt, after marking it as a favourite at the second)

At some point in future, when I'm not in a rush I'll boot up my laptop (gotta walk up two flights of stairs as well 🤣) and try using Chrome (so google gets my data now instead of Apple who I trust more 🤓) on Microsoft Windows (so Microsoft get my data too now 😝) and see if that works....or you guys can fix it before I do that and let me know at stephen.bowker AT Ericsson.com.

Yours, enjoying you excellent content, without being a member,

Steve

**Comment by spb2021** [comment]
I don't really want to enable "Cross-Site Tracking" but if that's the issue then let me know, and I **may** enable it just for you (but I'm not sure if Safari on IOS can be set that way)

**Comment by jerodsanto** [comment]
> Your sign-up page has room for improvement 😎

You are absolutely correct. Thanks for the detailed feedback 😎 

> Firstly, whatever I try I cannot get past the CAPTCHA check

It appears you're using private browsing mode? I know Cloudflare usually fails first attempts with that on. That being said, I don't think the captcha is re-rendering properly after an initial fail, so I will work on fixing that issue.

> if a user restarts safari after they encounter an error, it only remembers some of the entered items, even if it does remember the URL

I just tried this and I think every field is remembered _except_ the avatar/file field.

> the username (I think that's what the field is called, but it's a pain to go back and look whilst this form is being entered into) only accepts lower case letters (hmm Linux server at the back end methinks) so it would be useful to put a comment saying that somewhere where it will be noticed when entering the first time, rather than waiting for the error message.

Good call this is a bad UX. I'll improve it and report back.

> Whenever an error occurs, you deleted the data in the field for the Avatar image...

Hmm that sucks for sure. I'll look into how to get iOS to remember that file submission between form renders.
