### ISSUE TITLE
Newsletter in aerc lacks line breaks

### ISSUE THREAD

**Issue by lbergnehr** [thechangelog/changelog.com#473]
When viewing the newsletter in the plain text email client [aerc](https://aerc-mail.org/) it appears to lack linebreaks, printing the whole letter on the first line (unless there's word wrapping in the viewer).

**Comment by jerodsanto** [comment]
aerc lists this feature:

> Render HTML emails with an interactive terminal web browser

Do you know if that is being used or is it actually viewing the plaintext version of our email?

**Comment by lbergnehr** [comment]
> Do you know if that is being used or is it actually viewing the plaintext version of our email?

It has the `text/plain` part selected. If I switch to the `text/html` part, it shows up with my HTML filter pipeline (`pandoc` etc.) and is what I would expect.

**Comment by brentjanderson** [comment]
Dropping in to add on to this. Although the `pandoc` filter works enough to make it readable, having an intentionally formatted plaintext email would be nice. If it's not worth the trouble there is a decent path forward as-is using the `pandoc` filter, and this issue could be closed.

**Comment by jerodsanto** [comment]
The source of the email is written in Markdown, so I would expect the plaintext version to be pretty legible. I'm happy to make (reasonable) changes to make it a better experience for y'all, but I don't have a great way to iterate on the design and test it in a plaintext email client. Any advice on how to do that without major hassle?

**Comment by brentjanderson** [comment]
Not sure what your typical test pipeline looks like, but if you view the raw source of the sent message you can see that it lacks any line breaks:

<img width="827" alt="image" src="https://github.com/thechangelog/changelog.com/assets/45031/7a9c2a49-58c6-4500-a170-3942e39dcd68">

Here's one that has better formatting from Hilel Wayne via Buttondown:

<img width="827" alt="image" src="https://github.com/thechangelog/changelog.com/assets/45031/559844e1-c897-4c63-b2e1-c530c3761cbc">

> Iterate and test a plaintext email

Those screenshots are from Apple Mail (Under View > Message > Raw Source). 

<img width="705" alt="image" src="https://github.com/thechangelog/changelog.com/assets/45031/dc1d8538-3717-482c-ba38-90b8df7d9ce2">

If you have a way to tweak your design & view the raw email contents, that should do the trick.

**Comment by jerodsanto** [comment]
Actually you know what, I see now that I'm converting the Markdown to plaintext to send this part. Instead, I'll just keep it as Markdown and see if that's a better experience for you.

**Comment by brentjanderson** [comment]
That would be terrific if it is an easy change!

Again, there is a reasonable (IMO) workaround using the Pandoc filter in Aerc. This is what that same Changelog email looks like with the default Aerc + Pandoc instructions set up:

<img width="627" alt="image" src="https://github.com/thechangelog/changelog.com/assets/45031/a6d3a1ff-b78d-4198-97f2-a920399e8b72">

`aerc.conf` reference if someone else stumbles across this in the future:

```
[filters]
# ... Lots of filters in here by default ... #
# Uncomment the line that looks like this:
text/html=pandoc -f html -t markdown | colorize
```

**Comment by jerodsanto** [comment]
Super easy! https://github.com/thechangelog/changelog.com/commit/e3be94f5711ed0a2208fabd3b43a9918c2f34285

Let's close this as fixed (since it will certainly have line breaks on Monday) and if there are further things we can do to improve your reading experience, please open new issues!

**Comment by brentjanderson** [comment]
<img width="443" alt="image" src="https://github.com/thechangelog/changelog.com/assets/45031/938cf4f5-60e2-4dae-9094-d6938fb8f634">

Looks great to me!

**Comment by lbergnehr** [comment]
Look great! Thanks!
