### ISSUE TITLE
DX on DX editing issue

### ISSUE THREAD

**Issue by austinChappell** [thechangelog/changelog.com#479]
Around the 58:30 mark of the DX in DX episode, there is an editing issue where the voices are overlapping quite a bit. I don't know how long it goes on. I had to turn it off. I am using the baked-in iOS podcast app.

**Comment by jerodsanto** [comment]
Thanks for the heads up! We fixed it and pushed out a new mp3 to the feed, but apps that already downloaded the original file will need to manually re-download.
