### ISSUE TITLE
Bugs in negated `in` expressions

### ISSUE THREAD

**Issue by gorosgobe** [thechangelog/changelog.com#483]
`in` and `instanceof` expressions in JS
```js
a in obj;
a instanceof C;
```
can be negated by grouping them and applying the `!` operator, i.e.

```js
!(a in obj);
!(a instanceof C);
```

Applying the `!` operator incorrectly (on the LHS operand) leads to bugs:
```js
!a in obj; // will evaluate to false, unless obj has a "true" or "false" key
!a instanceof C; // will evaluate to false, unless C overrides instanceof with a @@hasInstance method
```
For more information, please see these [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#not_an_instanceof) and [the no-unsafe-negation recommended Eslint rule](https://eslint.org/docs/latest/rules/no-unsafe-negation).

I have found a potentially problematic instance of the above bugs in your codebase:
https://github.com/thechangelog/changelog.com/blob/ddd00d03e3bbe3c6b417facc92ebf981e79d306c/assets/app/modules/onsitePlayer.js#L449

**Comment by patHyatt** [comment]
@gorosgobe Beautiful issue. Its gorgeous and wonderfully documented

I did a [search](https://github.com/search?q=repo%3Athechangelog%2Fchangelog.com+%22+in+%22++language%3AJavaScript+&type=code) of the repo looking for any other cases which looks to only identify the file mentioned.

**Comment by gerhard** [comment]
WDYT @jerodsanto?
