### ISSUE TITLE
CDN cache misses increased 7x after Oct. 8, 2023

### ISSUE THREAD

**Issue by gerhard** [thechangelog/changelog.com#486]
## What is the problem?

[After Oct. 8, 2023, CDN cache misses increased by `7x`, from `0.75m` to `5.2m`](https://ui.honeycomb.io/changelog/datasets/fastly/result/EWGEsUbqxdQ)

![image](https://github.com/thechangelog/changelog.com/assets/3342/10390598-68c6-4b16-8f12-792bb3eda664)

This seems to be coming from the app origin, specifically `F_fly_2022_03_13`

[If we group by `url`](https://ui.honeycomb.io/changelog/datasets/fastly/result/BE5k1d2ZELJ), we notice that `/feed`, `/` & `/feed/` requests are the ones with the highest increase in cache misses:

<img width="1178" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/c93e6b7b-eddd-4466-89f5-c8497c82e5c8">

What is the Fastly response if we enable debug headers?

<img width="756" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/be7e562d-1ff5-40ab-bc75-7643d8d48e90">

This looks like a clean cache miss, and we do not have shielding enabled. [Fixed it](https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/166,167).

> **Note**
> While at it, [I did the same for the feeds origin](https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/167,168).

## Does this fix it?

This looks a lot better now:

<img width="1374" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/2f3f62d5-48c1-42cc-b6e3-17e2c6248f0e">

👉 Let's give this a few hours before we check the hits vs misses again.

### Do the cache headers look correct?

Looking at a specific URL endpoint served by the origin, we see the following:

<img width="755" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/b71dc7aa-851e-4d3b-ac00-a42b098bf639">

This looks correct to me. `surrogate-control` is set and should have precedence over `cache-control`. Reference: [Understand how cache control headers work](https://docs.fastly.com/en/guides/caching-best-practices#understand-how-cache-control-headers-work).

If the `surrogate-control` headers are respected, why does this content have so many misses? cc @jamesarosen

### Could this config change be related to the increased cache misses?

We had a two VCL changes earlier that day:
- [Gerhard enables HTTP/3 QUIC](https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/164,165)
- [Gerhard removes AWS S3 surrogate headers - now on Cloudflare R2](https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/165,166)

The second one looks suspicious, but on closer inspection we are simply setting `surrogate-control` to AWS S3 headers which are prefixed with `x-amz-meta-`:

![image](https://github.com/thechangelog/changelog.com/assets/3342/6c9a41c1-8afc-4f32-99fd-7e323f761475)

Could the above change be related to the increased cache misses @jamesarosen?

To be continued...

**Comment by jerodsanto** [comment]
Hmmm I never set up `/feed` to be served directly from R2 even though we are pre-generating it like all the other feeds now. No need to hit the app origin for this. Should I make that change @gerhard and see if this makes it all better?

**Comment by jerodsanto** [comment]
I went ahead and made this change so now every `/feed` request is being sent to R2 origin instead of the app origin:

```
curl -I https://changelog.com/feed
HTTP/2 200
content-type: application/xml
etag: W/"59b2e72e41e688450a1ca572543e9d20"
last-modified: Sun, 22 Oct 2023 13:17:46 GMT
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=DRcCdyhiCjkzqQ%2FdYsrHq%2BQqAbg%2FKpWp1k35Qeckvca3COcoQB8P8JJ3fAwp8aWKb12c2Tt0C3kL6RL0ETFFFDsX181Hal%2BK9%2F4OrxKkapP1ds2IBIguMea5q5jyPfVB5w4myw%2BJoLc%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
cache-control: max-age=3600, s-maxage=604800, stale-while-revalidate=604800, stale-if-error=604800
server: cloudflare
cf-ray: 81a20c6928694e03-MCI
access-control-allow-origin: *
accept-ranges: bytes
date: Sun, 22 Oct 2023 13:22:32 GMT
via: 1.1 varnish
age: 12
x-served-by: cache-mci680073-MCI
x-cache: HIT
x-cache-hits: 1
x-timer: S1697980952.206757,VS0,VE1
vary: Accept-Encoding
strict-transport-security: max-age=31557600
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 224492
```

**Comment by gerhard** [comment]
OK! That is an improvement for the `/feed` endpoint: https://ui.honeycomb.io/changelog/datasets/fastly/result/F3QLxZ2CAtp

![image](https://github.com/thechangelog/changelog.com/assets/3342/dde94c9f-9531-42d3-8d94-20fb113c01fc)

Want to do the same for `/feed/` & `/feed.json` ?

**Comment by gerhard** [comment]
@jerodsanto I have a placeholder Fastly config that re-enables shielding for both the app & the feeds origin: https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/169,170

Are you OK to have this enabled? I ask because I'm not sure if removing shielding on the app in https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/167,169 was intentional.

BTW, I just noticed that I never activated `v168`: https://manage.fastly.com/configure/services/7gKbcKSKGDyqU7IuDr43eG/diff/167,168

**Comment by gerhard** [comment]
Even after the `/feed` switch to R2, I still don't understand why `/` cache misses increased more than `10x`: https://ui.honeycomb.io/changelog/datasets/fastly/result/FQjroVdMo3E

<img width="1188" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/f93a3a70-386e-4b87-80e8-02455d94d866">

Time to run this by Fastly support.

**Comment by jamesarosen** [comment]
> The second one looks suspicious, but on closer inspection we are simply setting surrogate-control to AWS S3 headers which are prefixed with x-amz-meta-

The diff shows you _deleting_ that logic, not adding it.

> Want to do the same for /feed/ & /feed.json

What's the difference between `/feed` and `/feed/`? Instead of serving the same content from both, you'll get better caching if you rewrite or redirect the path at the edge.

> removing shielding on the app

Why? Given your global audience, shielding is definitely going to help you keep CHR high.

> Even after the /feed switch to R2, I still don't understand why / cache misses increased more than 10x

Can you show the `curl` / `httpstat` for the origin request for `/` and `/feed`?

**Comment by gerhard** [comment]
> The diff shows you deleting that logic, not adding it.

Yes, we deleted that logic, because we no longer need it (we replaced S3 with R2).

Since app responses do not use `x-amz-meta-` headers, deleting that logic shouldn't have had an impact on this, and yet it looks like they did - problems started happening at the same time, as captured in my previous comment.

> What's the difference between /feed and /feed/? Instead of serving the same content from both, you'll get better caching if you rewrite or redirect the path at the edge.

No difference. Yes, makes sense, that should be a rewrite at the edge.

> Given your global audience, shielding is definitely going to help you keep CHR high.

Yes, I'm pretty sure that we want to keep shielding for all origins. Want to double-check with @jerodsanto in case he had a good reason to disable it on the app. Perhaps it's related to the Websockets work that he did a few weeks back: https://changelog.slack.com/archives/C03SA8VE2/p1695996344381799 (the following 10 messages have more context).

> Can you show the `curl` / `httpstat` for the origin request for `/` and `/feed`?

Let's ignore `/feed` now, since that origin has changed to R2. Let's focus on `/` instead.

This is what the request to origin currently returns:

```sh
httpstat https://changelog-nightly-2023-10-10.fly.dev/

Connected to 66.241.124.151:443 from 192.168.88.18:52378

HTTP/2 200
server: Fly/55f8eaa0 (2023-10-09)
date: Sun, 22 Oct 2023 17:23:59 GMT
content-type: text/html
content-length: 759854
last-modified: Sun, 22 Oct 2023 02:59:25 GMT
accept-ranges: bytes
etag: "6534900d-b982e"
via: 2 fly.io
fly-request-id: 01HDC6MFE1Y342E2SZ8FZNPNSS-lhr

Body stored in: /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/tmpmm0el5v_

  DNS Lookup   TCP Connection   TLS Handshake   Server Processing   Content Transfer
[     5ms    |       5ms      |      6ms      |       94ms        |       268ms      ]
             |                |               |                   |                  |
    namelookup:5ms            |               |                   |                  |
                        connect:10ms          |                   |                  |
                                    pretransfer:16ms              |                  |
                                                      starttransfer:110ms            |
                                                                                 total:378ms
```

And here is the same request to Fastly:

```sh
httpstat https://changelog.com/
Connected to 151.101.129.162:443 from 192.168.88.18:52383

HTTP/2 200
cache-control: no-store, must-revalidate
content-type: text/html; charset=utf-8
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
server: Fly/55f8eaa0 (2023-10-09)
x-changelog-vanity-redirect: false
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: F5B91xd3BIDdNqgBIcCh
via: 1.1 fly.io, 1.1 varnish
fly-request-id: 01HDC6KYH20EX58WHF21A24427-lhr
access-control-allow-origin: *
accept-ranges: bytes
date: Sun, 22 Oct 2023 17:24:55 GMT
age: 73
x-served-by: cache-lon4265-LON
x-cache: HIT
x-cache-hits: 1
x-timer: S1697995496.598494,VS0,VE1
vary: Accept-Encoding
strict-transport-security: max-age=31557600
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 60890

Body stored in: /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/tmpccsfo978

  DNS Lookup   TCP Connection   TLS Handshake   Server Processing   Content Transfer
[     7ms    |       4ms      |      6ms      |        4ms        |        4ms       ]
             |                |               |                   |                  |
    namelookup:7ms            |               |                   |                  |
                        connect:11ms          |                   |                  |
                                    pretransfer:17ms              |                  |
                                                      starttransfer:21ms             |
                                                                                 total:25ms
```

And another request to Fastly:

```sh
httpstat https://changelog.com/
Connected to 151.101.129.162:443 from 192.168.88.18:52384

HTTP/2 200
cache-control: no-store, must-revalidate
content-type: text/html; charset=utf-8
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
server: Fly/55f8eaa0 (2023-10-09)
x-changelog-vanity-redirect: false
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: F5B96CwMXESe9kwAjrRi
via: 1.1 fly.io, 1.1 varnish
fly-request-id: 01HDC6P65JHTS4GRNVBVEH6SZ5-lhr
access-control-allow-origin: *
accept-ranges: bytes
date: Sun, 22 Oct 2023 17:25:07 GMT
age: 11
x-served-by: cache-lon420124-LON
x-cache: HIT
x-cache-hits: 1
x-timer: S1697995507.000441,VS0,VE1
vary: Accept-Encoding
strict-transport-security: max-age=31557600
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 60862

Body stored in: /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/tmpaxw8mrmh

  DNS Lookup   TCP Connection   TLS Handshake   Server Processing   Content Transfer
[     6ms    |       3ms      |     10ms      |        5ms        |        4ms       ]
             |                |               |                   |                  |
    namelookup:6ms            |               |                   |                  |
                        connect:9ms           |                   |                  |
                                    pretransfer:19ms              |                  |
                                                      starttransfer:24ms             |
                                                                                 total:28ms
```

While this looks good, we continue seeing a high rate of misses: `449` misses vs `289` hits in the last `1h`: https://ui.honeycomb.io/changelog/datasets/fastly/result/oJz39TUUryB

![image](https://github.com/thechangelog/changelog.com/assets/3342/7843f8e6-513a-4523-b769-3c3e27dbe4cf)

This is how that changed in the last 14 days vs 14 days prior: https://ui.honeycomb.io/changelog/datasets/fastly/result/4nwqn3VMREu

![image](https://github.com/thechangelog/changelog.com/assets/3342/f526aff5-8aa1-4903-ad3a-3050a77edbce)

**Comment by gerhard** [comment]
To make debugging this easier, I am attaching the current VCL config `v169`. Yes, I definitely intend to version control this in our repository.

[7gKbcKSKGDyqU7IuDr43eG_169.vcl.txt](https://github.com/thechangelog/changelog.com/files/13064086/7gKbcKSKGDyqU7IuDr43eG_169.vcl.txt)

**Comment by jamesarosen** [comment]
`https://changelog-nightly-2023-10-10.fly.dev/` doesn't have any `cache-control` or `surrogate-control` headers. Should it? Even if it changes pretty frequently, you could get some benefit from something like

```
cache-control: private, max-age=3600, must-revalidate
surrogate-control: public, max-age=60, stale-while-revalidate=3600
```

**Comment by gerhard** [comment]
Sorry @jamesarosen, that paste was my bad. It should have been:

```sh
httpstat https://changelog-2022-03-13.fly.dev/
Connected to 66.51.126.203:443 from 192.168.88.18:61248

HTTP/2 200
cache-control: no-store, must-revalidate
content-length: 60923
content-type: text/html; charset=utf-8
date: Tue, 24 Oct 2023 07:10:40 GMT
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
server: Fly/55f8eaa0 (2023-10-09)
surrogate-control: max-age=60, stale-while-revalidate=60, stale-if-error=604800
surrogate-key: pages
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: F5D5jDFXU3h2Ar8CmxuB
via: 2 fly.io
fly-request-id: 01HDG8AW9KDVKY0Y5QGTBGH22S-lhr

Body stored in: /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/tmpndfxmb7l

  DNS Lookup   TCP Connection   TLS Handshake   Server Processing   Content Transfer
[     6ms    |       4ms      |      7ms      |       355ms       |       157ms      ]
             |                |               |                   |                  |
    namelookup:6ms            |               |                   |                  |
                        connect:10ms          |                   |                  |
                                    pretransfer:17ms              |                  |
                                                      starttransfer:372ms            |
                                                                                 total:529ms
```

**Comment by jerodsanto** [comment]
@gerhard me disabling shielding when adding `/feed` to R2 was unintentional. I believe it was because I cloned the wrong version of the config or something...

I just now activated Version 170 now, which re-enables shielding on both the app and feed origins.

**Comment by GIPeon** [comment]
Sorry to hijack does this have anything to do with 404s on https://changelog.com/master/feed ? 
Thanks

**Comment by jerodsanto** [comment]
Yes it does @GIPeon thanks for mentioning. 

@gerhard all feed endpoints were 404ing with shielding on. It appears that Fastly was forwarding to Fly for these instead of Cloudflare. I disabled shielding on the feeds origin, cleared cache, and we back with 200s once again.

I'm not sure why the shielding would cause this, though...

**Comment by jamesarosen** [comment]
Usually, if enabling shielding causes 404s, it’s because some routing condition you expect to be true is no longer true because you’re modified the request at the edge.

Less often, it’s because you’ve cached 404 responses in the shield.

**Comment by jerodsanto** [comment]
@gerhard I also just disabled shielding to the Fly origin because when it's on we lose the ability to detect the original host requested (eg - changelog.com, x.changelog.com, etc).

The code I'm using to do that (which maybe we can adjust to still work with shielding on) is this:

```elixir
def get_host(conn) do
    host = get_header(conn, "x-forwarded-host") || get_header(conn, "host") || Map.get(conn, :host, nil)

    host
    |> to_string()
    |> String.split(":")
    |> List.first()
  end
```

This works with shielding off, doesn't with it on.

**Comment by jamesarosen** [comment]
> This works with shielding off, doesn't with it on.

This is an excellent hint!

### My hypothesis

For requests that don't use the shield, you're getting

```
host: x.changelog.com
```

But for requests that use the shield, you've overridden the host.

This configuration causes Fastly to change the `host` header:
```
backend F_fly_2022_03_13 {
    .always_use_host_header = true;
    .host = "changelog-2022-03-13.fly.dev";
    .host_header = "changelog-2022-03-13.fly.dev";
```

So if you `set req.backend = F_fly_2022_03_13` at the edge, the request at shield will have `host: changelog-2022-03-13.fly.dev` and won't match routing rules that check `req.host`.

### Potential Solutions

Most of the host-based logic doesn't really need to run at both edge and shield. You could add `req.restarts == 0` to the condition to make sure those things only happen at edge, and not at shield.

You could save off the original host very early in the request:

```vcl
if (req.restarts == 0 && !req.http.original-host) {
  req.http.original-host = req.http.host;
}
```

and then use `req.http.original-host` to do your logic.

See [Specifying an override host](https://docs.fastly.com/en/guides/specifying-an-override-host)

**Comment by gerhard** [comment]
> all feed endpoints were 404ing with shielding on. It appears that Fastly was forwarding to Fly for these instead of Cloudflare. I disabled shielding on the feeds origin, cleared cache, and we back with 200s once again.

Got it! This confirms the problem: https://ui.honeycomb.io/changelog/datasets/fastly/result/JMomht9BuJu

<img width="1189" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/a455e4c4-24f9-4ffb-8266-29502dd10a93">

We now have a trigger in Honeycomb that will send me a notification if that happens again: https://ui.honeycomb.io/changelog/datasets/fastly/triggers/8pENCV13L76 . If you want @jerodsanto, we can notify you as well.

> I also just disabled shielding to the Fly origin because when it's on we lose the ability to detect the original host requested (eg - changelog.com, x.changelog.com, etc).

Interesting.

@jamesarosen explanation makes sense to me. To double-check that I understood it correctly:
- I am attaching out current VCL config, [`175`](https://github.com/thechangelog/changelog.com/files/13174139/7gKbcKSKGDyqU7IuDr43eG_175.vcl.txt)
- I am attaching a modified VCL config, [`v176`](https://github.com/thechangelog/changelog.com/files/13174148/7gKbcKSKGDyqU7IuDr43eG_176.vcl.txt), **WHICH IS NOT YET ACTIVE**

Do the changes look good to you @jamesarosen?

In the meantime, if you need to make another VCL change @jerodsanto, please ensure that you are starting from `v175`, otherwise we may end up with a config change that is not ready to go out.

**Comment by jamesarosen** [comment]
> Do the changes look good to you @jamesarosen?

I think they're worth a shot! They certainly look safe enough to try.

**Comment by gerhard** [comment]
OK, I have just activated `v176`, let's see how this goes!

**Comment by gerhard** [comment]
That didn't work as expected: https://ui.honeycomb.io/changelog/datasets/fastly/result/8fAqcgcYS4s

![image](https://github.com/thechangelog/changelog.com/assets/3342/b7613fc1-6389-447f-a841-5a98554dcc85)

**Comment by jamesarosen** [comment]
I'm glad things have stabilized. Configuration changes like this often result in a lot of cache misses at first, so the brief spike isn't surprising.

The only change I _might_ make would be to change

```vcl
if (req.restarts == 0 && !req.http.original-host) {
```

to

```vcl
if (req.restarts == 0) {
```

That way, an attacker can't inject a fake `original-host` header. In this particular case, I don't think it will matter. It's just a good general practice to be defensive about your variables.

**Comment by gerhard** [comment]
I should have been clearer in my previous message, but I had to revert back to `v175` to fix this problem. There must be something missing in the diff that prevents the feeds origin from serving feeds correctly.

Shortly after I enabled config `v176`, my first screenshot shows elevated `404` responses for all feeds. The trigger notified me and I reverted back to `v175`. All back to normal afterwards.

My next step is to set this up on my replica setup, and figure out what I'm missing there, instead of introducing more errors in the production setup.

In case you want to help debug this further, I have attached both `v175` & `v176` in full in one of my previous comments. This week is full-on for me, no sync time available. Next week looks much better though in case you would like to sync @jamesarosen.

**Comment by gerhard** [comment]
Last action item follow-up: I set up https://cloudflare.changelog.place on Cloudflare, but I cannot complete the integration since `Host Header Override` is only available to Enterprise users - [source](https://blog.cloudflare.com/origin-rules):

<img width="921" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/c159c01e-f54f-4529-97b9-2e61b9c3ec50">

Without this feature, Cloudflare is sending the `cloudflare.changelog.place` host to Fly.io which it does not recognise, and it redirects to `changelog.com`. This results in an infinite redirect loop:

<img width="969" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/788a77f2-8654-479b-9859-72686e63d831">

Following-up privately with @adamstac re Cloudflare.

**Comment by gerhard** [comment]
Closing since this is done from my perspective.

OK to reopen if following-up in this context makes sense.
