### ISSUE TITLE
(Mix) Unknown repository "oban", add new repositories with the `mix hex.repo add` task

### ISSUE THREAD

**Issue by gerhard** [thechangelog/changelog.com#494]
Since https://github.com/thechangelog/changelog.com/pull/472, I am getting the following failure in dev:

```console
(Mix) Unknown repository "oban", add new repositories with the `mix hex.repo add` task
```

While I am able to solve this by adding the oban repository with the oban license key, external contributors will not be able to do this.

If we want to keep this app contributions friendly, I think that we should address this.

WDYT @jerodsanto? cc @sorentwo

---
<img width="773" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/9fa0816c-5b5b-4058-8275-e13c6509c03a">

**Comment by jerodsanto** [comment]
Yeah this one is tough. If someone who has `OBAN_LICENSE_KEY` env var runs `mix deps.get` and checks the resulting `mix.lock` in, it breaks things for folks who don't have it. If the alternative happens, it breaks it for folks who do...

Not sure what the best solution here is...

**Comment by sorentwo** [comment]
I’ll work on a PR so this can work either way.

**Comment by sorentwo** [comment]
@gerhard Actually, it looks like the situation you encountered is already handled in `mix.exs` with [a conditional check](https://github.com/thechangelog/changelog.com/blob/aade90a1bed7c70e947f0462197b888ec695fbcd/mix.exs#L5). It tried to download the package because you have the `OBAN_LICENSE_KEY` env set.

@jerodsanto Unlocking `oban_web` before fetching will work around that. Maybe we can add an alias that combines both operations and instruct contributors to use that instead of `deps.get`?

```elixir
defp aliases do
  [
    "deps.safe_get": ["deps.unlock oban_web", "deps.get"]
  ...
```

**Comment by gerhard** [comment]
@sorentwo I was assuming that the conditional would work too, but it doesn't: 
<img width="774" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/10c06894-f69a-40b2-8e54-79588ac10ea2">

Even when the conditional is commented, and we only remain with `@oban_envs [:prod]`, I am still getting the same error:
<img width="790" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/532fb29a-c01f-4123-a429-48625c8b6a4c">

**Comment by sorentwo** [comment]
@gerhard I took a few minutes to investigate this and remembered it's because the default `deps.get` fetches packages for all environments. You must use `deps.get --only dev` to restrict it to only fetching dev packages. Try adding this alias and using it to fetch instead:

```elixir
"deps.get_dev": ["deps.unlock oban_web oban_met", "deps.get --only dev"]
```

That should omit those packages as expected, and ensure that they aren't included the the resulting `mix.lock`.

**Comment by gerhard** [comment]
That was helpful @sorentwo! I've made the change to `CONTRIBUTING.md` which will work for external contributors.

**Comment by gerhard** [comment]
This issue is back since https://github.com/thechangelog/changelog.com/compare/kaizen.13...master

What surprises me is that I have no local hex or mix state, and I have removed all `repo: "oban"` instances, and yet `mix deps.get --only test` still fails:

<img width="791" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/6ba1446f-304c-4cd8-b3f3-33419d0a230f">

<img width="1278" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/936ebcb0-db86-4588-b433-8be480e9702c">

@sorentwo would you know where info about this repository is stored in Hex/Mix?

**Comment by gerhard** [comment]
FTR:

<img width="719" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/0fd83abb-35e6-49cd-9b8d-5d912d791815">

**Comment by sorentwo** [comment]
The dependencies are entirely listed in `mix.lock`. In the screenshot above you've removed/unlocked `oban_web`, but not `oban_met`, which is also served privately from the `oban` repo.

**Comment by jerodsanto** [comment]
I added that alias to our `mix.exs` and just pushed to GH with both of those packages removed from `mix.lock` 🤞

**Comment by jerodsanto** [comment]
That did fix the issue, thanks for repeating yourself @sorentwo! 💚

**Comment by sorentwo** [comment]
No problem! 💛

**Comment by gerhard** [comment]
Thank you for the second round @sorentwo!

If I understood correctly, the issue was `oban_web` which was accidentally committed to `mix.lock` part of https://github.com/thechangelog/changelog.com/commit/62b0b689efc72adc18faa3064484d8763ae4e11d. Even though I removed it, because I left `oban_met` there, the commands that we had in place - `mix deps.get --only dev` - stopped working. This fixed it: https://github.com/thechangelog/changelog.com/commit/e0e027769a969ee6b1a8b121d8e8d39fa54f2496

I am pretty sure that this issue will come back if we do not guard against `oban_web` & `oban_met` being added to `mix.lock` by accident. From my side, this is OK, since I have left enough breadcrumbs for myself to know how to fix this in the future if needed.

Are you OK with this resolution @jerodsanto?

**Comment by sorentwo** [comment]
It will be fine if those entries are left in mix.lock, provided you use the `mix deps.get_dev` alias to fetch packages. Unlocking removes the packages from mix.lock and then the conditional only adds them back when the license key is set.
