### ISSUE TITLE
When logged in, loading the home page can take more than 30s

### ISSUE THREAD

**Issue by gerhard** [thechangelog/changelog.com#506]
@jamietanna reported that loading the home page can take more than `30s` (when logged in). Here is the rest of the context:
<img width="779" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/0c31eac7-4a9a-4469-8d86-e1853b93798f">

I looked at `/` HTTP traces in Honeycomb.io for the last 24 hours: https://ui.honeycomb.io/changelog/datasets/changelog_opentelemetry/result/86KqyuLrLmb?hideCompare

<img width="1440" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/dd25cc96-f307-4117-a7c3-2555f8f316b9">

<br>While we do have some outliers: e.g. `1.5s`, `1.3s`, they are nowhere near `30s`, let's look at that `1.6s` outlier:
<img width="1440" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/fc57c252-b017-49bc-8f74-199967816f12">

So most of that time - `614.9ms` - is spent querying episodes from the db. While that is not an insignificant amount of time, it's not what we are looking for.

If I widen the search scope and look for all `GET changelog.com` requests served by Fastly in the last 24h (minus a few outliers, like `feed`, `search`, etc.), there are just a few which stand out (slowest one is `10s`): https://ui.honeycomb.io/changelog/datasets/fastly/result/dJxisPkzbJp

<img width="1440" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/130c26b1-b6b5-4457-97ad-27ec5fffc73b">

<br>And here is the trace for it: https://ui.honeycomb.io/changelog/datasets/changelog_opentelemetry/result/wR6SQPxNh6q/trace/2Ejtkjs5VwY?fields[]=s_name&fields[]=s_serviceName&source=query&span=bb1e31e1c5a67c96

<img width="1440" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/4c5e55a2-34cc-4811-b794-bf384f7e81ee">

That is still not it, so let's focus just on `/` requests in the last 7 days which took more than `1s` - we get 7 results: https://ui.honeycomb.io/changelog/datasets/changelog_opentelemetry/result/BPS39ES6kgo

<img width="1440" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/c2c29015-434b-48ea-8b02-e8d76990bac4">

<br>If I focus on the longest one - `2.3s` - then I see something similar (episodes db query taking `1.356s`), but nothing too crazy: https://ui.honeycomb.io/changelog/datasets/changelog_opentelemetry/result/BPS39ES6kgo/trace/8ejX45oRVYX?fields[]=s_name&fields[]=s_serviceName&source=query&span=8baf0b91a347e470

<img width="1440" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/d1070601-0b0e-4007-8a5e-a3fa69592bb8">

## How do we debug further?
Before we can debug this further, next time this happens, we will need:
- Exact timestamp (preferably in UTC)
- Exact URL used
- Public IP address (private DM is fine)

That should be be enough to find the specific request trace.

Also, if you can share your public IP address @jamietanna, I could filter all requests and look at how they behaved from our end.

Thank you for the report!

**Comment by jamietanna** [comment]
Thanks @gerhard! I can't seem to replicate it on my laptop (connected to the same local internet) so when I'm back at my desktop I'll try to reproduce.

Interestingly, when I last tried it it kept on going - with no response for > ~5 minutes - without a timeout, so it's very odd.

I'll try and reproduce - and share my IP privately via Slack DM - and let you know

**Comment by gerhard** [comment]
[I looked at all app traces served to your IP in the last 2 weeks](https://ui.honeycomb.io/changelog/datasets/changelog_opentelemetry/result/squwdJ99Dh7). 99% of them get served in `271ms`

<img width="1286" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/913ea601-f750-4db2-b6f3-e65e883143fd">

---
[I then looked at all `changelog.com` responses served to your IP in the last 2 weeks](https://ui.honeycomb.io/changelog/datasets/fastly/result/ERbVUxHJzHs).

These are served by Fastly, and 99% of them get served in `620ms`:

<img width="1293" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/ffb09e61-19f3-4b72-989c-16224a89e3f4">

---

[The slowest `changelog.com` response served to you was `/master/feed`, which took `1.4s`](https://ui.honeycomb.io/changelog/datasets/fastly/result/cQ5aLc8sf5n):


<img width="1291" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/f9a8ff7b-7a64-4b53-86ae-b02e2345ebc5">

---
[Other responses which took longer than `1.4s` to serve were `audio/mpeg` files](https://ui.honeycomb.io/changelog/datasets/fastly/result/jGpUiLXiLGE), which is expected:

![image](https://github.com/thechangelog/changelog.com/assets/3342/e0e14d02-7f81-4e89-8633-e6d74b18baeb)

---

Bottom line is that everything is behaving as expected server-side.

If you want me to help you troubleshoot this, a few things that I will need when this happens again:

**1/3. What does the slow request duration breakdown look like on your end?**

I personally use `httpstat` for this, which shows DNS, TCP, TLS, etc. e.g.

<img width="763" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/1dd73830-d928-4e85-b017-4c82b4429a2e">


**2/3. Does the origin behave the same?**

I am using the same `httpstat` command as above, but going directly to the Origin, **not** the CDN:

<img width="760" alt="image" src="https://github.com/thechangelog/changelog.com/assets/3342/64ea1f33-2fbd-4e7e-9f5c-4563b7b627b3">

In my case, using the CDN means 20x quicker responses (`20ms` vs `400ms`).


**3/3. Do you get the same behaviour from a different host?**

As you mentioned earlier, this looks like a client-side issue to me. I am re-running the same `httpstat` request from a laptop which is connected to my secondary home network:

<img width="664" alt="Screenshot 2024-02-25 at 13 59 25" src="https://github.com/thechangelog/changelog.com/assets/3342/3de07812-6937-4175-87af-d45d053eed95">

Notice how poorly it performed in comparison: `6426ms` vs `20ms` from my first `httpstat` run!

The truth is that if I switch to WiFi 6 & the DNS is already cached, then I get a consistent `40ms`:

<img width="663" alt="Screenshot 2024-02-25 at 14 00 32" src="https://github.com/thechangelog/changelog.com/assets/3342/cecb1507-1b47-4ed5-9ebf-d1f525eef315">

Let me know how it goes!

**Comment by jamietanna** [comment]
As discussed in DMs, I think this could be closed - I've not seen this again since it first occurred, but will definitely keep an eye and re-raise if I see it (as well as try and do a bit more debugging my side)

**Comment by gerhard** [comment]
Thanks @jamietanna for the follow-up, closing this now.

**Comment by jamietanna** [comment]
FYI @gerhard this appears to have resurfaced :thinking:

Not seeing it happening in direct-to-Fly URLs, just the https://changelog.com/

I was having pages just loading forever (~5 minutes and counting for some)

Interestingly, I've found that I could resolve it by doing a cache reset refresh, didn't get a chance to do any debugging further than that, sorry!
