### ISSUE TITLE
The links in the confirmation main are broken

### ISSUE THREAD

**Issue by volkanunsal** [thechangelog/changelog.com#519]
Unable to confirm email after signing up.

**Comment by jerodsanto** [comment]
Can you provide more information? Such as:

- Your email client
- What happens when you click on the link
- Your browser

**Comment by volkanunsal** [comment]
Gmail
It redirects me to a broken link
I’m using Chrome

**Comment by jerodsanto** [comment]
Can you paste the link that you have in your gmail here and maybe a screenshot of the page you land on?

**Comment by volkanunsal** [comment]
<img width="1172" alt="Screenshot 2024-08-02 at 9 40 49 AM" src="https://github.com/user-attachments/assets/fcf77a7b-98c4-409b-b171-a58132ced24f">
<img width="1146" alt="Screenshot 2024-08-02 at 9 41 06 AM" src="https://github.com/user-attachments/assets/8ec84c9c-3ac0-487d-abfa-3f16e6bb4295">

**Comment by jerodsanto** [comment]
ok that's super weird because we don't do any link tracking or rewrites of our links. That "confirm my account" button should link directly to `https://changelog.com/in/{your-auth-token-here]`

Can you hover on that and see if it's not the case?

**Comment by volkanunsal** [comment]
The url of the button is exactly the same one as the one in the browser you're seeing here.

**Comment by volkanunsal** [comment]
All the other links in the email are mangled as well.

**Comment by jerodsanto** [comment]
This seems like maybe a fluke with our transactional email provider. I checked a bunch of others of the same email and all the links are fine, but this one is not. I'm going to trigger another send and see if it comes through correctly this time.

**Comment by volkanunsal** [comment]
Yup, that worked. Thanks for the help.

**Comment by jerodsanto** [comment]
Cool, sorry for the hassle!
