### ISSUE TITLE
Error 500 when deleting a custom feed

### ISSUE THREAD

**Issue by maroskucera** [thechangelog/changelog.com#528]
When deleting an old custom feed, I get error 500. If I create a new custom feed, I'm able to delete it, but an old feed (ID 16 for example) throws 500. I've tried multiple steps to replicate the issue with new feeds. I've opened the actual feed, refreshed the feed and then opened it, but the deletion worked flawlessly on those.

Let me know if there is more info I can provide 🙂

**Comment by jerodsanto** [comment]
I believe this one is fixed. Please reopen if you find otherwise...

**Comment by maroskucera** [comment]
I can confirm, my old feeds have been put out to pasture 😇
