### ISSUE TITLE
Formal Request: No more "Frameworkism"

### ISSUE THREAD

**Issue by AbdhilahiRWabwire** [thechangelog/changelog.com#537]
Dear honorable Master Engineers of Changelog Media, I respect thee greatly. I am not as wise as my Master Engineer colleagues, but "Frameworkism" is dishonorable and extremely damaging to all of Engineering. It could infect other Engineering disciplines with it's viral outbreak. Master Engineer Jerod Santo understands this. Please follow Master Jerod's lead on this sensitive topic. React/next.js/Vercel/Angular have more than enough followers and developer advocates to convert the entire planet of Earth into React Andy's. Here is a series of articles to reference with links: 

https://infrequently.org/2024/11/if-not-react-then-what/

Here is a list of Browser APIs that Software Engineers are ignoring, as a reference point:

https://developer.mozilla.org/en-US/docs/Web/API

Encouraging the adoption of Browser APIs, Native Interfaces and Standard Libraries of Programming Languages instead of "Frameworkism", would benefit the entirety of Software Engineering as a whole. I formally request your assistance in this matter.

Furthermore, the metric volume of Web Development job postings requiring React or Angular, speaks for itself. Witness it on LinkedIn, Indeed or your preferred job posting site, lest I speak outlandishly. Pardon my timber.

**Comment by jerodsanto** [comment]
> Master Engineer Jerod Santo

brb gotta go update my linkedin profile!
