### ISSUE TITLE
Posts with funky styles 

### ISSUE THREAD

**Issue by heatherstac** [thechangelog/changelog.com#84]
I went through some of the posts to see if anything really stood out. These are some of the posts that I saw that kind of seemed a little awkward looking. I would say spacing, line-height, etc...

https://changelog.com/posts/essential-reading-list-for-getting-started-with-service-workers
https://changelog.com/posts/must-watch-videos-service-workers
Equal spacing - https://changelog.com/posts/improving-your-sql-skills
https://changelog.com/posts/feed-the-bridge-troll

**Comment by jerodsanto** [comment]
This is pretty stale, closing for cleanliness ✨
