### ISSUE TITLE
Rename slug bug

### ISSUE THREAD

**Issue by adamstac** [thechangelog/changelog.com#88]
I published this, then unpublished to change the slug (love that I can do that) -- but I think because I uploaded the file before the slug change it can't play the file because the file name doesn't match the slug anymore.

Here's the URL https://2016.changelog.com/podcast/bonus-153

The slug was `teaser-153`, but is now `bonus-153`.

**Comment by gerhard** [comment]
Pretty sure that this is no longer relevant and we should close it. It's OK to re-open if you think otherwise.
